from .acl_scope import *
from .acl_scope_event import *
from .attendee_chat_member import *
from .batch_delete_calendar_event_attendee_request import *
from .batch_delete_calendar_event_attendee_request_body import *
from .batch_delete_calendar_event_attendee_response import *
from .book_meeting_room_data import *
from .calendar import *
from .calendar_acl import *
from .calendar_acl_event import *
from .calendar_attendee_resource_customization import *
from .calendar_event import *
from .calendar_event_attendee import *
from .calendar_event_attendee_chat_member import *
from .calendar_event_attendee_id import *
from .calendar_event_attendee_resp import *
from .calendar_event_resp import *
from .calendar_freebusy import *
from .calendar_freebusy_error import *
from .card_callback import *
from .card_present import *
from .create_calendar_acl_request import *
from .create_calendar_acl_response import *
from .create_calendar_acl_response_body import *
from .create_calendar_event_attendee_request import *
from .create_calendar_event_attendee_request_body import *
from .create_calendar_event_attendee_response import *
from .create_calendar_event_attendee_response_body import *
from .create_calendar_event_request import *
from .create_calendar_event_response import *
from .create_calendar_event_response_body import *
from .create_calendar_request import *
from .create_calendar_response import *
from .create_calendar_response_body import *
from .create_exchange_binding_request import *
from .create_exchange_binding_response import *
from .create_exchange_binding_response_body import *
from .create_timeoff_event_request import *
from .create_timeoff_event_response import *
from .create_timeoff_event_response_body import *
from .customization_option import *
from .delete_calendar_acl_request import *
from .delete_calendar_acl_response import *
from .delete_calendar_event_request import *
from .delete_calendar_event_response import *
from .delete_calendar_request import *
from .delete_calendar_response import *
from .delete_exchange_binding_request import *
from .delete_exchange_binding_response import *
from .delete_timeoff_event_request import *
from .delete_timeoff_event_response import *
from .event_card import *
from .event_location import *
from .event_search_filter import *
from .event_time import *
from .exchange_binding import *
from .free_time import *
from .freebusy import *
from .generate_caldav_conf_setting_request import *
from .generate_caldav_conf_setting_request_body import *
from .generate_caldav_conf_setting_response import *
from .generate_caldav_conf_setting_response_body import *
from .get_calendar_event_request import *
from .get_calendar_event_response import *
from .get_calendar_event_response_body import *
from .get_calendar_request import *
from .get_calendar_response import *
from .get_calendar_response_body import *
from .get_exchange_binding_request import *
from .get_exchange_binding_response import *
from .get_exchange_binding_response_body import *
from .list_calendar_acl_request import *
from .list_calendar_acl_response import *
from .list_calendar_acl_response_body import *
from .list_calendar_event_attendee_chat_member_request import *
from .list_calendar_event_attendee_chat_member_response import *
from .list_calendar_event_attendee_chat_member_response_body import *
from .list_calendar_event_attendee_request import *
from .list_calendar_event_attendee_response import *
from .list_calendar_event_attendee_response_body import *
from .list_calendar_event_request import *
from .list_calendar_event_response import *
from .list_calendar_event_response_body import *
from .list_calendar_request import *
from .list_calendar_response import *
from .list_calendar_response_body import *
from .list_freebusy_request import *
from .list_freebusy_request_body import *
from .list_freebusy_response import *
from .list_freebusy_response_body import *
from .meeting_chat import *
from .meeting_minute import *
from .meeting_settings import *
from .myai_card_status import *
from .myai_reply import *
from .operate_card_data import *
from .p2_calendar_calendar_acl_created_v4 import *
from .p2_calendar_calendar_acl_deleted_v4 import *
from .p2_calendar_calendar_changed_v4 import *
from .p2_calendar_calendar_event_changed_v4 import *
from .patch_calendar_event_request import *
from .patch_calendar_event_response import *
from .patch_calendar_event_response_body import *
from .patch_calendar_request import *
from .patch_calendar_response import *
from .patch_calendar_response_body import *
from .primary_calendar_request import *
from .primary_calendar_response import *
from .primary_calendar_response_body import *
from .reminder import *
from .room_meta import *
from .schema import *
from .search_calendar_event_request import *
from .search_calendar_event_request_body import *
from .search_calendar_event_response import *
from .search_calendar_event_response_body import *
from .search_calendar_request import *
from .search_calendar_request_body import *
from .search_calendar_response import *
from .search_calendar_response_body import *
from .setting import *
from .subscribe_calendar_request import *
from .subscribe_calendar_response import *
from .subscribe_calendar_response_body import *
from .subscription_calendar_acl_request import *
from .subscription_calendar_acl_response import *
from .subscription_calendar_event_request import *
from .subscription_calendar_event_response import *
from .subscription_calendar_request import *
from .subscription_calendar_response import *
from .time_info import *
from .timeoff_event import *
from .unsubscribe_calendar_request import *
from .unsubscribe_calendar_response import *
from .unsubscription_calendar_acl_request import *
from .unsubscription_calendar_acl_response import *
from .unsubscription_calendar_event_request import *
from .unsubscription_calendar_event_response import *
from .unsubscription_calendar_request import *
from .unsubscription_calendar_response import *
from .user_calendar import *
from .user_id import *
from .vc_info import *
from .vchat import *
