# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class MgetCalendarRequestBody(object):
    _types = {
        "calendar_ids": List[str],
    }

    def __init__(self, d=None):
        self.calendar_ids: Optional[List[str]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "MgetCalendarRequestBodyBuilder":
        return MgetCalendarRequestBodyBuilder()


class MgetCalendarRequestBodyBuilder(object):
    def __init__(self) -> None:
        self._mget_calendar_request_body = MgetCalendarRequestBody()

    def calendar_ids(self, calendar_ids: List[str]) -> "MgetCalendarRequestBodyBuilder":
        self._mget_calendar_request_body.calendar_ids = calendar_ids
        return self

    def build(self) -> "MgetCalendarRequestBody":
        return self._mget_calendar_request_body
