# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class RoomApprovalInfo(object):
    _types = {
        "approval_mode": str,
        "approval_duration_threshold": str,
    }

    def __init__(self, d=None):
        self.approval_mode: Optional[str] = None
        self.approval_duration_threshold: Optional[str] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "RoomApprovalInfoBuilder":
        return RoomApprovalInfoBuilder()


class RoomApprovalInfoBuilder(object):
    def __init__(self) -> None:
        self._room_approval_info = RoomApprovalInfo()

    def approval_mode(self, approval_mode: str) -> "RoomApprovalInfoBuilder":
        self._room_approval_info.approval_mode = approval_mode
        return self

    def approval_duration_threshold(
        self, approval_duration_threshold: str
    ) -> "RoomApprovalInfoBuilder":
        self._room_approval_info.approval_duration_threshold = (
            approval_duration_threshold
        )
        return self

    def build(self) -> "RoomApprovalInfo":
        return self._room_approval_info
