# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.model import BaseRequest
from lark_oapi.core.enum import HttpMethod, AccessTokenType


class SubscriptionCalendarRequest(BaseRequest):
    def __init__(self) -> None:
        super().__init__()

    @staticmethod
    def builder() -> "SubscriptionCalendarRequestBuilder":
        return SubscriptionCalendarRequestBuilder()


class SubscriptionCalendarRequestBuilder(object):

    def __init__(self) -> None:
        subscription_calendar_request = SubscriptionCalendarRequest()
        subscription_calendar_request.http_method = HttpMethod.POST
        subscription_calendar_request.uri = "/open-apis/calendar/v4/calendars/subscription"
        subscription_calendar_request.token_types = {AccessTokenType.USER}
        self._subscription_calendar_request: SubscriptionCalendarRequest = subscription_calendar_request

    def build(self) -> SubscriptionCalendarRequest:
        return self._subscription_calendar_request
