# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class UserTaskOpinion(object):
    _types = {
        "content": str,
    }

    def __init__(self, d=None):
        self.content: Optional[str] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "UserTaskOpinionBuilder":
        return UserTaskOpinionBuilder()


class UserTaskOpinionBuilder(object):
    def __init__(self) -> None:
        self._user_task_opinion = UserTaskOpinion()

    def content(self, content: str) -> "UserTaskOpinionBuilder":
        self._user_task_opinion.content = content
        return self

    def build(self) -> "UserTaskOpinion":
        return self._user_task_opinion
