from .avatar_info import *
from .chat_member_user import *
from .chat_i18n_names import *
from .chat_restricted_mode_setting import *
from .collaboration_department import *
from .collaboration_department_id import *
from .collaboration_department_leader import *
from .collaboration_entity import *
from .collaboration_tenant import *
from .collaboration_user import *
from .collaboration_user_id import *
from .custom_attr_generic_user import *
from .department_i18n_name import *
from .department_id import *
from .department_leader import *
from .department_status import *
from .event_message import *
from .event_sender import *
from .i18n_content import *
from .i18n_name import *
from .invalid_id import *
from .job_title import *
from .mention import *
from .mention_event import *
from .message import *
from .message_body import *
from .sender import *
from .share_department import *
from .share_user import *
from .trust_party_app_to_tenants import *
from .user_custom_attr import *
from .user_custom_attr_value import *
from .user_id import *
from .user_status import *
from .get_collaboration_tenant_request import *
from .list_collaboration_tenant_request import *
from .visible_organization_collaboration_tenant_request import *
from .get_collaboration_tenant_collaboration_department_request import *
from .get_collaboration_tenant_collaboration_user_request import *
from .get_collaboration_tenant_response_body import *
from .get_collaboration_tenant_response import *
from .list_collaboration_tenant_response_body import *
from .list_collaboration_tenant_response import *
from .visible_organization_collaboration_tenant_response_body import *
from .visible_organization_collaboration_tenant_response import *
from .get_collaboration_tenant_collaboration_department_response_body import *
from .get_collaboration_tenant_collaboration_department_response import *
from .get_collaboration_tenant_collaboration_user_response_body import *
from .get_collaboration_tenant_collaboration_user_response import *
