# -*- coding: UTF-8 -*-
# Code generated by lark suite oapi sdk gen

from typing import List, Dict, Any
import attr




@attr.s
class Image(object):
    pass



@attr.s
class ImageBasicRecognizeReqBody(object):
    image = attr.ib(type=str, default=None, metadata={'json': 'image'})
    image_key = attr.ib(type=str, default=None, metadata={'json': 'image_key'})


@attr.s
class ImageBasicRecognizeResult(object):
    text_list = attr.ib(type=List[str], default=None, metadata={'json': 'text_list'})