# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class AiUsageNote(object):
    _types = {
        "key_name": str,
        "key_type": int,
        "value": str,
    }

    def __init__(self, d=None):
        self.key_name: Optional[str] = None
        self.key_type: Optional[int] = None
        self.value: Optional[str] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "AiUsageNoteBuilder":
        return AiUsageNoteBuilder()


class AiUsageNoteBuilder(object):
    def __init__(self) -> None:
        self._ai_usage_note = AiUsageNote()

    def key_name(self, key_name: str) -> "AiUsageNoteBuilder":
        self._ai_usage_note.key_name = key_name
        return self

    def key_type(self, key_type: int) -> "AiUsageNoteBuilder":
        self._ai_usage_note.key_type = key_type
        return self

    def value(self, value: str) -> "AiUsageNoteBuilder":
        self._ai_usage_note.value = value
        return self

    def build(self) -> "AiUsageNote":
        return self._ai_usage_note
