# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .bot_menu_redirect_link import BotMenuRedirectLink
from .bot_menu_ud_icon import BotMenuUdIcon


class BotMenuConfig1(object):
    _types = {
        "default_name": str,
        "i18n_name": Dict[str, str],
        "redirect_link": BotMenuRedirectLink,
        "event_key": str,
        "icon_file_key": str,
        "ud_icon": BotMenuUdIcon,
        "menu_content_type": int,
    }

    def __init__(self, d=None):
        self.default_name: Optional[str] = None
        self.i18n_name: Optional[Dict[str, str]] = None
        self.redirect_link: Optional[BotMenuRedirectLink] = None
        self.event_key: Optional[str] = None
        self.icon_file_key: Optional[str] = None
        self.ud_icon: Optional[BotMenuUdIcon] = None
        self.menu_content_type: Optional[int] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "BotMenuConfig1Builder":
        return BotMenuConfig1Builder()


class BotMenuConfig1Builder(object):
    def __init__(self) -> None:
        self._bot_menu_config1 = BotMenuConfig1()

    def default_name(self, default_name: str) -> "BotMenuConfig1Builder":
        self._bot_menu_config1.default_name = default_name
        return self

    def i18n_name(self, i18n_name: Dict[str, str]) -> "BotMenuConfig1Builder":
        self._bot_menu_config1.i18n_name = i18n_name
        return self

    def redirect_link(
        self, redirect_link: BotMenuRedirectLink
    ) -> "BotMenuConfig1Builder":
        self._bot_menu_config1.redirect_link = redirect_link
        return self

    def event_key(self, event_key: str) -> "BotMenuConfig1Builder":
        self._bot_menu_config1.event_key = event_key
        return self

    def icon_file_key(self, icon_file_key: str) -> "BotMenuConfig1Builder":
        self._bot_menu_config1.icon_file_key = icon_file_key
        return self

    def ud_icon(self, ud_icon: BotMenuUdIcon) -> "BotMenuConfig1Builder":
        self._bot_menu_config1.ud_icon = ud_icon
        return self

    def menu_content_type(self, menu_content_type: int) -> "BotMenuConfig1Builder":
        self._bot_menu_config1.menu_content_type = menu_content_type
        return self

    def build(self) -> "BotMenuConfig1":
        return self._bot_menu_config1
