from .activity_record import *
from .activity_session_info import *
from .activity_session_record import *
from .certificate import *
from .certificate_acquisition import *
from .completion_condition import *
from .course import *
from .course_category import *
from .course_channel import *
from .course_lecture import *
from .course_object import *
from .course_registration import *
from .department_id import *
from .event_course_registration import *
from .event_user import *
from .exam_record import *
from .external_user import *
from .i18n import *
from .lesson import *
from .lesson_study_record import *
from .scope_entry_date_info import *
from .session import *
from .stage_info import *
from .task_info import *
from .train_program import *
from .train_program_registration import *
from .training import *
from .training_registration import *
from .user import *
from .user_id import *
from .visible_scope_group import *
from .visible_scope_info import *
from .visible_scope_unit import *
from .p2_elearning_course_registration_created_v2 import *
from .p2_elearning_course_registration_deleted_v2 import *
from .p2_elearning_course_registration_updated_v2 import *
