from .attachment import *
from .attachment_download_url_item import *
from .department_id import *
from .email_alias import *
from .event_log import *
from .file_meta_info import *
from .folder import *
from .mail_address import *
from .mail_contact import *
from .mail_flow_rule_info import *
from .mail_log import *
from .mail_log_mail_info import *
from .mailgroup import *
from .mailgroup_manager import *
from .mailgroup_member import *
from .mailgroup_permission_member import *
from .message import *
from .public_mailbox import *
from .public_mailbox_member import *
from .rule import *
from .rule_action import *
from .rule_action_item import *
from .rule_condition import *
from .rule_condition_item import *
from .subscriber import *
from .user import *
from .user_id import *
from .user_info import *
from .user_mail_entity import *
from .create_mailgroup_request import *
from .delete_mailgroup_request import *
from .get_mailgroup_request import *
from .list_mailgroup_request import *
from .patch_mailgroup_request import *
from .update_mailgroup_request import *
from .create_mailgroup_alias_request import *
from .delete_mailgroup_alias_request import *
from .list_mailgroup_alias_request import *
from .batch_create_mailgroup_manager_request_body import *
from .batch_create_mailgroup_manager_request import *
from .batch_delete_mailgroup_manager_request_body import *
from .batch_delete_mailgroup_manager_request import *
from .list_mailgroup_manager_request import *
from .batch_create_mailgroup_member_request_body import *
from .batch_create_mailgroup_member_request import *
from .batch_delete_mailgroup_member_request_body import *
from .batch_delete_mailgroup_member_request import *
from .create_mailgroup_member_request import *
from .delete_mailgroup_member_request import *
from .get_mailgroup_member_request import *
from .list_mailgroup_member_request import *
from .batch_create_mailgroup_permission_member_request_body import *
from .batch_create_mailgroup_permission_member_request import *
from .batch_delete_mailgroup_permission_member_request_body import *
from .batch_delete_mailgroup_permission_member_request import *
from .create_mailgroup_permission_member_request import *
from .delete_mailgroup_permission_member_request import *
from .get_mailgroup_permission_member_request import *
from .list_mailgroup_permission_member_request import *
from .create_public_mailbox_request import *
from .delete_public_mailbox_request import *
from .get_public_mailbox_request import *
from .list_public_mailbox_request import *
from .patch_public_mailbox_request import *
from .remove_to_recycle_bin_public_mailbox_request_body import *
from .remove_to_recycle_bin_public_mailbox_request import *
from .update_public_mailbox_request import *
from .create_public_mailbox_alias_request import *
from .delete_public_mailbox_alias_request import *
from .list_public_mailbox_alias_request import *
from .batch_create_public_mailbox_member_request_body import *
from .batch_create_public_mailbox_member_request import *
from .batch_delete_public_mailbox_member_request_body import *
from .batch_delete_public_mailbox_member_request import *
from .clear_public_mailbox_member_request import *
from .create_public_mailbox_member_request import *
from .delete_public_mailbox_member_request import *
from .get_public_mailbox_member_request import *
from .list_public_mailbox_member_request import *
from .query_user_request_body import *
from .query_user_request import *
from .delete_user_mailbox_request import *
from .create_user_mailbox_alias_request import *
from .delete_user_mailbox_alias_request import *
from .list_user_mailbox_alias_request import *
from .subscribe_user_mailbox_event_request_body import *
from .subscribe_user_mailbox_event_request import *
from .subscription_user_mailbox_event_request import *
from .unsubscribe_user_mailbox_event_request_body import *
from .unsubscribe_user_mailbox_event_request import *
from .create_user_mailbox_folder_request import *
from .delete_user_mailbox_folder_request import *
from .list_user_mailbox_folder_request import *
from .patch_user_mailbox_folder_request import *
from .create_user_mailbox_mail_contact_request import *
from .delete_user_mailbox_mail_contact_request import *
from .list_user_mailbox_mail_contact_request import *
from .patch_user_mailbox_mail_contact_request import *
from .get_user_mailbox_message_request import *
from .get_by_card_user_mailbox_message_request import *
from .list_user_mailbox_message_request import *
from .send_user_mailbox_message_request import *
from .download_url_user_mailbox_message_attachment_request import *
from .create_user_mailbox_rule_request import *
from .delete_user_mailbox_rule_request import *
from .list_user_mailbox_rule_request import *
from .reorder_user_mailbox_rule_request_body import *
from .reorder_user_mailbox_rule_request import *
from .update_user_mailbox_rule_request import *
from .create_mailgroup_response_body import *
from .create_mailgroup_response import *
from .delete_mailgroup_response import *
from .get_mailgroup_response_body import *
from .get_mailgroup_response import *
from .list_mailgroup_response_body import *
from .list_mailgroup_response import *
from .patch_mailgroup_response_body import *
from .patch_mailgroup_response import *
from .update_mailgroup_response_body import *
from .update_mailgroup_response import *
from .create_mailgroup_alias_response_body import *
from .create_mailgroup_alias_response import *
from .delete_mailgroup_alias_response import *
from .list_mailgroup_alias_response_body import *
from .list_mailgroup_alias_response import *
from .batch_create_mailgroup_manager_response import *
from .batch_delete_mailgroup_manager_response import *
from .list_mailgroup_manager_response_body import *
from .list_mailgroup_manager_response import *
from .batch_create_mailgroup_member_response_body import *
from .batch_create_mailgroup_member_response import *
from .batch_delete_mailgroup_member_response import *
from .create_mailgroup_member_response_body import *
from .create_mailgroup_member_response import *
from .delete_mailgroup_member_response import *
from .get_mailgroup_member_response_body import *
from .get_mailgroup_member_response import *
from .list_mailgroup_member_response_body import *
from .list_mailgroup_member_response import *
from .batch_create_mailgroup_permission_member_response_body import *
from .batch_create_mailgroup_permission_member_response import *
from .batch_delete_mailgroup_permission_member_response import *
from .create_mailgroup_permission_member_response_body import *
from .create_mailgroup_permission_member_response import *
from .delete_mailgroup_permission_member_response import *
from .get_mailgroup_permission_member_response_body import *
from .get_mailgroup_permission_member_response import *
from .list_mailgroup_permission_member_response_body import *
from .list_mailgroup_permission_member_response import *
from .create_public_mailbox_response_body import *
from .create_public_mailbox_response import *
from .delete_public_mailbox_response import *
from .get_public_mailbox_response_body import *
from .get_public_mailbox_response import *
from .list_public_mailbox_response_body import *
from .list_public_mailbox_response import *
from .patch_public_mailbox_response_body import *
from .patch_public_mailbox_response import *
from .remove_to_recycle_bin_public_mailbox_response import *
from .update_public_mailbox_response_body import *
from .update_public_mailbox_response import *
from .create_public_mailbox_alias_response_body import *
from .create_public_mailbox_alias_response import *
from .delete_public_mailbox_alias_response import *
from .list_public_mailbox_alias_response_body import *
from .list_public_mailbox_alias_response import *
from .batch_create_public_mailbox_member_response_body import *
from .batch_create_public_mailbox_member_response import *
from .batch_delete_public_mailbox_member_response import *
from .clear_public_mailbox_member_response import *
from .create_public_mailbox_member_response_body import *
from .create_public_mailbox_member_response import *
from .delete_public_mailbox_member_response import *
from .get_public_mailbox_member_response_body import *
from .get_public_mailbox_member_response import *
from .list_public_mailbox_member_response_body import *
from .list_public_mailbox_member_response import *
from .query_user_response_body import *
from .query_user_response import *
from .delete_user_mailbox_response import *
from .create_user_mailbox_alias_response_body import *
from .create_user_mailbox_alias_response import *
from .delete_user_mailbox_alias_response import *
from .list_user_mailbox_alias_response_body import *
from .list_user_mailbox_alias_response import *
from .subscribe_user_mailbox_event_response import *
from .subscription_user_mailbox_event_response_body import *
from .subscription_user_mailbox_event_response import *
from .unsubscribe_user_mailbox_event_response import *
from .create_user_mailbox_folder_response_body import *
from .create_user_mailbox_folder_response import *
from .delete_user_mailbox_folder_response import *
from .list_user_mailbox_folder_response_body import *
from .list_user_mailbox_folder_response import *
from .patch_user_mailbox_folder_response import *
from .create_user_mailbox_mail_contact_response_body import *
from .create_user_mailbox_mail_contact_response import *
from .delete_user_mailbox_mail_contact_response import *
from .list_user_mailbox_mail_contact_response_body import *
from .list_user_mailbox_mail_contact_response import *
from .patch_user_mailbox_mail_contact_response import *
from .get_user_mailbox_message_response_body import *
from .get_user_mailbox_message_response import *
from .get_by_card_user_mailbox_message_response_body import *
from .get_by_card_user_mailbox_message_response import *
from .list_user_mailbox_message_response_body import *
from .list_user_mailbox_message_response import *
from .send_user_mailbox_message_response import *
from .download_url_user_mailbox_message_attachment_response_body import *
from .download_url_user_mailbox_message_attachment_response import *
from .create_user_mailbox_rule_response_body import *
from .create_user_mailbox_rule_response import *
from .delete_user_mailbox_rule_response import *
from .list_user_mailbox_rule_response_body import *
from .list_user_mailbox_rule_response import *
from .reorder_user_mailbox_rule_response import *
from .update_user_mailbox_rule_response import *
from .p2_mail_user_mailbox_event_message_received_v1 import *
