# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .email_info import EmailInfo


class AccessibleMailboxesUserMailboxResponseBody(object):
    _types = {
        "accessible_mailboxes": List[EmailInfo],
    }

    def __init__(self, d=None):
        self.accessible_mailboxes: Optional[List[EmailInfo]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "AccessibleMailboxesUserMailboxResponseBodyBuilder":
        return AccessibleMailboxesUserMailboxResponseBodyBuilder()


class AccessibleMailboxesUserMailboxResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._accessible_mailboxes_user_mailbox_response_body = AccessibleMailboxesUserMailboxResponseBody()

    def accessible_mailboxes(self, accessible_mailboxes: List[
        EmailInfo]) -> "AccessibleMailboxesUserMailboxResponseBodyBuilder":
        self._accessible_mailboxes_user_mailbox_response_body.accessible_mailboxes = accessible_mailboxes
        return self

    def build(self) -> "AccessibleMailboxesUserMailboxResponseBody":
        return self._accessible_mailboxes_user_mailbox_response_body
