# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.model import BaseRequest
from lark_oapi.core.enum import HttpMethod, AccessTokenType


class DeleteUserMailboxTemplateRequest(BaseRequest):
    def __init__(self) -> None:
        super().__init__()
        self.user_mailbox_id: Optional[str] = None
        self.template_id: Optional[str] = None

    @staticmethod
    def builder() -> "DeleteUserMailboxTemplateRequestBuilder":
        return DeleteUserMailboxTemplateRequestBuilder()


class DeleteUserMailboxTemplateRequestBuilder(object):

    def __init__(self) -> None:
        delete_user_mailbox_template_request = DeleteUserMailboxTemplateRequest()
        delete_user_mailbox_template_request.http_method = HttpMethod.DELETE
        delete_user_mailbox_template_request.uri = "/open-apis/mail/v1/user_mailboxes/:user_mailbox_id/templates/:template_id"
        delete_user_mailbox_template_request.token_types = {AccessTokenType.USER, AccessTokenType.TENANT}
        self._delete_user_mailbox_template_request: DeleteUserMailboxTemplateRequest = delete_user_mailbox_template_request

    def user_mailbox_id(self, user_mailbox_id: str) -> "DeleteUserMailboxTemplateRequestBuilder":
        self._delete_user_mailbox_template_request.user_mailbox_id = user_mailbox_id
        self._delete_user_mailbox_template_request.paths["user_mailbox_id"] = str(user_mailbox_id)
        return self

    def template_id(self, template_id: str) -> "DeleteUserMailboxTemplateRequestBuilder":
        self._delete_user_mailbox_template_request.template_id = template_id
        self._delete_user_mailbox_template_request.paths["template_id"] = str(template_id)
        return self

    def build(self) -> DeleteUserMailboxTemplateRequest:
        return self._delete_user_mailbox_template_request
