# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .label import Label


class GetUserMailboxLabelResponseBody(object):
    _types = {
        "label": Label,
    }

    def __init__(self, d=None):
        self.label: Optional[Label] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "GetUserMailboxLabelResponseBodyBuilder":
        return GetUserMailboxLabelResponseBodyBuilder()


class GetUserMailboxLabelResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._get_user_mailbox_label_response_body = GetUserMailboxLabelResponseBody()

    def label(self, label: Label) -> "GetUserMailboxLabelResponseBodyBuilder":
        self._get_user_mailbox_label_response_body.label = label
        return self

    def build(self) -> "GetUserMailboxLabelResponseBody":
        return self._get_user_mailbox_label_response_body
