# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from lark_oapi.core.model import BaseResponse
from .get_user_mailbox_template_response_body import GetUserMailboxTemplateResponseBody


class GetUserMailboxTemplateResponse(BaseResponse):
    _types = {
        "data": GetUserMailboxTemplateResponseBody,

    }

    def __init__(self, d=None):
        super().__init__(d)
        self.data: Optional[GetUserMailboxTemplateResponseBody] = None
        init(self, d, self._types)
