# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .mail_contact import MailContact


class ListUserMailboxMailContactResponseBody(object):
    _types = {
        "items": List[MailContact],
        "page_token": str,
        "has_more": bool,
    }

    def __init__(self, d=None):
        self.items: Optional[List[MailContact]] = None
        self.page_token: Optional[str] = None
        self.has_more: Optional[bool] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "ListUserMailboxMailContactResponseBodyBuilder":
        return ListUserMailboxMailContactResponseBodyBuilder()


class ListUserMailboxMailContactResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._list_user_mailbox_mail_contact_response_body = ListUserMailboxMailContactResponseBody()

    def items(self, items: List[MailContact]) -> "ListUserMailboxMailContactResponseBodyBuilder":
        self._list_user_mailbox_mail_contact_response_body.items = items
        return self

    def page_token(self, page_token: str) -> "ListUserMailboxMailContactResponseBodyBuilder":
        self._list_user_mailbox_mail_contact_response_body.page_token = page_token
        return self

    def has_more(self, has_more: bool) -> "ListUserMailboxMailContactResponseBodyBuilder":
        self._list_user_mailbox_mail_contact_response_body.has_more = has_more
        return self

    def build(self) -> "ListUserMailboxMailContactResponseBody":
        return self._list_user_mailbox_mail_contact_response_body
