# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .public_mailbox_member import PublicMailboxMember


class ListPublicMailboxMemberResponseBody(object):
    _types = {
        "has_more": bool,
        "page_token": str,
        "items": List[PublicMailboxMember],
    }

    def __init__(self, d=None):
        self.has_more: Optional[bool] = None
        self.page_token: Optional[str] = None
        self.items: Optional[List[PublicMailboxMember]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "ListPublicMailboxMemberResponseBodyBuilder":
        return ListPublicMailboxMemberResponseBodyBuilder()


class ListPublicMailboxMemberResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._list_public_mailbox_member_response_body = ListPublicMailboxMemberResponseBody()

    def has_more(self, has_more: bool) -> "ListPublicMailboxMemberResponseBodyBuilder":
        self._list_public_mailbox_member_response_body.has_more = has_more
        return self

    def page_token(self, page_token: str) -> "ListPublicMailboxMemberResponseBodyBuilder":
        self._list_public_mailbox_member_response_body.page_token = page_token
        return self

    def items(self, items: List[PublicMailboxMember]) -> "ListPublicMailboxMemberResponseBodyBuilder":
        self._list_public_mailbox_member_response_body.items = items
        return self

    def build(self) -> "ListPublicMailboxMemberResponseBody":
        return self._list_public_mailbox_member_response_body
