# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from lark_oapi.core.model import BaseResponse
from .list_user_mailbox_folder_response_body import ListUserMailboxFolderResponseBody


class ListUserMailboxFolderResponse(BaseResponse):
    _types = {
        "data": ListUserMailboxFolderResponseBody
    }

    def __init__(self, d=None):
        super().__init__(d)
        self.data: Optional[ListUserMailboxFolderResponseBody] = None
        init(self, d, self._types)
