from .ability import *
from .ability_assessment import *
from .attachment import *
from .composite_talent import *
from .composite_talent_award_info import *
from .composite_talent_basic_info import *
from .composite_talent_career_info import *
from .composite_talent_customized_data import *
from .composite_talent_education_info import *
from .composite_talent_internship_info import *
from .composite_talent_language_info import *
from .composite_talent_project_info import *
from .composite_talent_self_introduction import *
from .composite_talent_sns_info import *
from .composite_talent_works_info import *
from .department_id import *
from .dimension_assessment import *
from .dimension_option import *
from .i18n import *
from .id_name_object import *
from .interview_record import *
from .module_assessment import *
from .question_assessment import *
from .recommended_job_level import *
from .record_score import *
from .registration_basic_info import *
from .talent_block import *
from .talent_customized_attachment import *
from .talent_customized_data_child import *
from .talent_customized_option import *
from .talent_customized_time_range import *
from .talent_customized_value import *
from .talent_folder import *
from .talent_interview_registration_simple import *
from .talent_note import *
from .talent_pool import *
from .talent_resume_attachment import *
from .talent_resume_source import *
from .talent_similar import *
from .talent_tag import *
from .get_interview_record_request import *
from .list_interview_record_request import *
from .get_talent_request import *
from .get_interview_record_response_body import *
from .get_interview_record_response import *
from .list_interview_record_response_body import *
from .list_interview_record_response import *
from .get_talent_response_body import *
from .get_talent_response import *
