# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from lark_oapi.core.model import BaseResponse
from .create_tenant_access_token_response_body import (
    CreateTenantAccessTokenResponseBody,
)


class CreateTenantAccessTokenResponse(BaseResponse):
    _types = {
        "data": CreateTenantAccessTokenResponseBody,
    }

    def __init__(self, d=None):
        super().__init__(d)
        self.data: Optional[CreateTenantAccessTokenResponseBody] = None
        init(self, d, self._types)
