from .abnormal_reason import *
from .abnormal_reason_element import *
from .abnormal_reason_i18n_element import *
from .address import *
from .address_for_update import *
from .approval_group import *
from .approver_info import *
from .assessment import *
from .assessment_for_create import *
from .bank import *
from .bank_account import *
from .bank_account_for_update import *
from .bank_branch import *
from .basic_department import *
from .basic_employee import *
from .basic_info import *
from .basic_info_update import *
from .basic_job_data import *
from .basic_person_info import *
from .bp import *
from .bpm_dataengine_i18n import *
from .bpm_flow_info import *
from .calculate_param import *
from .change_field_pair import *
from .citizenship_status import *
from .city import *
from .company import *
from .company_id_and_name import *
from .company_timeline import *
from .company_version_data import *
from .contract import *
from .cost_center import *
from .cost_center_version import *
from .country_region import *
from .country_region_subdivision import *
from .create_emp_custom_org import *
from .create_transfer_info import *
from .currency import *
from .custom_field_data import *
from .custom_name import *
from .custom_org import *
from .custom_org_create import *
from .custom_org_list import *
from .custom_org_update import *
from .custom_org_with_rate import *
from .custom_value import *
from .dataengine_i18n import *
from .department import *
from .department_adjust_record import *
from .department_change import *
from .department_for_patch import *
from .department_hrbp import *
from .department_id import *
from .department_parent_info import *
from .department_parents import *
from .department_timeline import *
from .department_tree import *
from .dependent import *
from .dependent_for_update import *
from .dimension import *
from .dimension_entity import *
from .dimension_id_in_data import *
from .dimension_info import *
from .dimension_info_data import *
from .dimension_value import *
from .district import *
from .draft_info import *
from .education import *
from .education_info import *
from .education_info_for_update import *
from .email import *
from .email_for_update import *
from .emergency_contact import *
from .emergency_contact_for_update import *
from .emp_custom_org_list import *
from .employee import *
from .employee_job_family import *
from .employee_job_level import *
from .employee_pathway import *
from .employee_bt import *
from .employee_domain_event_data import *
from .employee_international_assignment import *
from .employee_job_data import *
from .employees_additional_job import *
from .employees_additional_job_batch_req_date import *
from .employees_additional_job_edit import *
from .employees_additional_job_write_resp import *
from .employees_international_assignment import *
from .employees_international_assignment_req import *
from .employees_international_assignment_resp import *
from .employment import *
from .employment_bp import *
from .employment_leave_balance import *
from .enum import *
from .enum_field import *
from .enums import *
from .field_variable_sub_vlaue import *
from .field_variable_sub_vlaue_for_review import *
from .field_variable_value import *
from .field_variable_value_i18n import *
from .field_variable_value_to import *
from .field_variable_value_to_enum import *
from .field_variable_value_to_file import *
from .field_variable_value_to_file_for_write import *
from .field_variable_value_to_for_review import *
from .field_variable_value_to_object import *
from .field_variable_value_to_record import *
from .file import *
from .form_field_variable_bool_value import *
from .form_field_variable_i18n_value import *
from .form_field_variable_null_value import *
from .form_field_variable_number_value import *
from .form_field_variable_string_value import *
from .form_variable_value_info import *
from .hiberarchy_common import *
from .i18n import *
from .i18n_v2 import *
from .international_assignment import *
from .international_assignment_v2 import *
from .international_assignment_v2_for_create import *
from .international_assignment_v2_for_patch import *
from .job import *
from .job_change import *
from .job_data import *
from .job_data_cost_center import *
from .job_data_custom_org import *
from .job_family import *
from .job_family_timeline import *
from .job_family_version_data import *
from .job_grade import *
from .job_grade_create import *
from .job_grade_update import *
from .job_level import *
from .job_timeline import *
from .job_version_data import *
from .lang_text import *
from .language import *
from .leave_accrual_record import *
from .leave_balance import *
from .leave_employ_expire_record import *
from .leave_granting_record import *
from .leave_process_info import *
from .leave_request import *
from .leave_request_detail import *
from .location import *
from .location_address_create import *
from .location_address_update import *
from .location_timeline import *
from .location_update import *
from .location_v2 import *
from .location_version_data import *
from .match_rule import *
from .match_rules import *
from .name import *
from .name_for_update import *
from .national_id import *
from .national_id_for_update import *
from .nationality import *
from .notice_period_detail import *
from .object_field_data import *
from .offer_info import *
from .offer_info_update import *
from .onboarding_flow import *
from .onboarding_flow_change import *
from .onboarding_qr_code import *
from .onboarding_task import *
from .onboarding_task_change import *
from .operation_log_entity import *
from .operation_log_entity_field import *
from .operation_log_list_req import *
from .operation_log_list_resp_item import *
from .org_role import *
from .org_role_update import *
from .organization_domain_event_data import *
from .organization_op_log import *
from .orgdraft_department_id import *
from .pathway import *
from .pathway_create import *
from .pathway_update import *
from .person_info import *
from .person_info_bt import *
from .person_info_chn import *
from .person_name import *
from .personal_profile import *
from .personal_profile_for_update import *
from .phone import *
from .phone_for_update import *
from .phone_number_and_area_code import *
from .position import *
from .position_adjustment_info import *
from .position_change import *
from .position_create import *
from .position_update import *
from .pre_hire import *
from .pre_hire_abnormal_reason import *
from .pre_hire_contract_info import *
from .pre_hire_employment_info import *
from .pre_hire_onboarding_info import *
from .pre_hire_pay_group_info import *
from .pre_hire_probation_info import *
from .prehire_create import *
from .prehire_seniority_adjust_information import *
from .prehire_seniority_adjust_information_query import *
from .prehire_seniority_adjust_information_update import *
from .prehire_update import *
from .probation_info import *
from .probation_info_for_submit import *
from .process_approver import *
from .process_revoke_and_withdraw import *
from .process_abstract_item import *
from .process_cc_item import *
from .process_comment_info import *
from .process_done_item import *
from .process_extra import *
from .process_form_variable import *
from .process_form_variable_v2 import *
from .process_info import *
from .process_link import *
from .process_system_done_item import *
from .process_system_todo_item import *
from .process_todo_item import *
from .process_transfer import *
from .profile_setting_address import *
from .profile_setting_bank_account import *
from .profile_setting_career import *
from .profile_setting_citizenship_status import *
from .profile_setting_cost_center import *
from .profile_setting_custom_field import *
from .profile_setting_custom_group import *
from .profile_setting_custom_group_item import *
from .profile_setting_data_attachment import *
from .profile_setting_dependent import *
from .profile_setting_education import *
from .profile_setting_emergency_contact import *
from .profile_setting_emp_basic_info_for_update import *
from .profile_setting_emp_contract_record import *
from .profile_setting_emp_info_for_update import *
from .profile_setting_employment_basic_info import *
from .profile_setting_employment_info import *
from .profile_setting_employment_record import *
from .profile_setting_field_error import *
from .profile_setting_file import *
from .profile_setting_hukou import *
from .profile_setting_i18n import *
from .profile_setting_name import *
from .profile_setting_national import *
from .profile_setting_personal_basic_info import *
from .profile_setting_personal_info import *
from .profile_setting_personal_record import *
from .profile_setting_phone import *
from .profile_setting_probation_info import *
from .profile_setting_resident_tax import *
from .profile_setting_work_experience import *
from .qr_code import *
from .qr_code_dimension import *
from .qr_code_dimension_value import *
from .qr_code_value import *
from .reorganization_info import *
from .report_detail_req import *
from .resident_tax import *
from .resident_tax_for_update import *
from .seniority_adjust_information import *
from .seniority_adjust_information_edit import *
from .signature_custom_field_v1 import *
from .signature_custom_field_v2 import *
from .signature_custom_field_value import *
from .signature_custom_field_value_multilingual_value import *
from .signature_enum_info import *
from .signature_enum_info_label import *
from .signature_file import *
from .signature_file_system_field import *
from .signature_folder import *
from .signature_human_info import *
from .signature_meta_info import *
from .signature_node import *
from .signature_signatory_label import *
from .signature_template import *
from .signature_template_attachment_info import *
from .signature_template_brief_info import *
from .signature_template_combination_field_info import *
from .signature_template_combination_field_info_v2 import *
from .signature_template_combination_sub_field_info import *
from .signature_template_common_field_info import *
from .signature_template_content_info import *
from .signature_template_content_item import *
from .signature_template_custom_field import *
from .signature_template_field import *
from .signature_template_filter import *
from .signature_template_filter_item import *
from .signature_template_id_with_system_and_custom_field import *
from .signature_template_info import *
from .signature_template_info_with_thumbnail import *
from .signature_template_permission_info import *
from .signature_template_region_info import *
from .signature_template_setting import *
from .signature_user_info import *
from .start_process_param import *
from .terminate_signature_fail_id_and_reason import *
from .time_zone import *
from .tranfer_employment_info import *
from .transfer_info import *
from .user_contact import *
from .user_id import *
from .user_info import *
from .work_email import *
from .work_email_check_result import *
from .work_email_info_list import *
from .work_experience import *
from .work_experience_for_update import *
from .work_experience_info import *
from .workforce_plan import *
from .workforce_plan_detail import *
from .workforce_plan_detail_req import *
from .workforce_plan_detail_row import *
from .workforce_plan_detail_v2 import *
from .workforce_plan_eai_detail import *
from .workforce_plan_multi_period_value import *
from .get_approval_groups_request import *
from .open_query_department_change_list_by_ids_approval_groups_request_body import *
from .open_query_department_change_list_by_ids_approval_groups_request import *
from .open_query_job_change_list_by_ids_approval_groups_request_body import *
from .open_query_job_change_list_by_ids_approval_groups_request import *
from .list_approver_request import *
from .search_basic_info_bank_request_body import *
from .search_basic_info_bank_request import *
from .search_basic_info_bank_branch_request_body import *
from .search_basic_info_bank_branch_request import *
from .search_basic_info_city_request_body import *
from .search_basic_info_city_request import *
from .search_basic_info_country_region_request_body import *
from .search_basic_info_country_region_request import *
from .search_basic_info_country_region_subdivision_request_body import *
from .search_basic_info_country_region_subdivision_request import *
from .search_basic_info_currency_request_body import *
from .search_basic_info_currency_request import *
from .search_basic_info_district_request_body import *
from .search_basic_info_district_request import *
from .search_basic_info_language_request_body import *
from .search_basic_info_language_request import *
from .search_basic_info_nationality_request_body import *
from .search_basic_info_nationality_request import *
from .search_basic_info_time_zone_request_body import *
from .search_basic_info_time_zone_request import *
from .get_by_department_bp_request_body import *
from .get_by_department_bp_request import *
from .list_bp_request import *
from .active_company_request_body import *
from .active_company_request import *
from .batch_get_company_request_body import *
from .batch_get_company_request import *
from .query_recent_change_company_request import *
from .search_contract_request_body import *
from .search_contract_request import *
from .create_cost_center_request import *
from .delete_cost_center_request_body import *
from .delete_cost_center_request import *
from .patch_cost_center_request_body import *
from .patch_cost_center_request import *
from .query_recent_change_cost_center_request import *
from .search_cost_center_request_body import *
from .search_cost_center_request import *
from .create_cost_center_version_request import *
from .delete_cost_center_version_request_body import *
from .delete_cost_center_version_request import *
from .patch_cost_center_version_request_body import *
from .patch_cost_center_version_request import *
from .batch_get_department_request_body import *
from .batch_get_department_request import *
from .delete_department_request import *
from .parents_department_request_body import *
from .parents_department_request import *
from .patch_department_request import *
from .query_multi_timeline_department_request_body import *
from .query_multi_timeline_department_request import *
from .query_operation_logs_department_request_body import *
from .query_operation_logs_department_request import *
from .query_recent_change_department_request import *
from .query_timeline_department_request_body import *
from .query_timeline_department_request import *
from .search_department_request_body import *
from .search_department_request import *
from .tree_department_request_body import *
from .tree_department_request import *
from .batch_get_employee_request_body import *
from .batch_get_employee_request import *
from .create_employee_request_body import *
from .create_employee_request import *
from .search_employee_request_body import *
from .search_employee_request import *
from .batch_employees_additional_job_request_body import *
from .batch_employees_additional_job_request import *
from .create_employees_additional_job_request import *
from .delete_employees_additional_job_request import *
from .patch_employees_additional_job_request import *
from .batch_get_employees_bp_request_body import *
from .batch_get_employees_bp_request import *
from .batch_get_employees_job_data_request_body import *
from .batch_get_employees_job_data_request import *
from .query_employees_job_data_request_body import *
from .query_employees_job_data_request import *
from .search_enum_request_body import *
from .search_enum_request import *
from .get_job_request import *
from .list_job_request import *
from .create_job_change_request_body import *
from .create_job_change_request import *
from .revoke_job_change_request_body import *
from .revoke_job_change_request import *
from .search_job_change_request_body import *
from .search_job_change_request import *
from .batch_get_job_family_request_body import *
from .batch_get_job_family_request import *
from .query_recent_change_job_family_request import *
from .create_job_grade_request import *
from .delete_job_grade_request import *
from .patch_job_grade_request import *
from .query_job_grade_request_body import *
from .query_job_grade_request import *
from .query_recent_change_job_grade_request import *
from .batch_get_job_level_request_body import *
from .batch_get_job_level_request import *
from .query_recent_change_job_level_request import *
from .active_location_request_body import *
from .active_location_request import *
from .batch_get_location_request_body import *
from .batch_get_location_request import *
from .patch_location_request import *
from .query_recent_change_location_request import *
from .create_location_address_request import *
from .delete_location_address_request import *
from .patch_location_address_request import *
from .edit_offboarding_request_body import *
from .edit_offboarding_request import *
from .revoke_offboarding_request_body import *
from .revoke_offboarding_request import *
from .submit_v2_offboarding_request_body import *
from .submit_v2_offboarding_request import *
from .create_person_request import *
from .patch_person_request import *
from .complete_pre_hire_request import *
from .create_pre_hire_request import *
from .delete_pre_hire_request import *
from .patch_pre_hire_request import *
from .query_pre_hire_request_body import *
from .query_pre_hire_request import *
from .restore_flow_instance_pre_hire_request_body import *
from .restore_flow_instance_pre_hire_request import *
from .search_pre_hire_request_body import *
from .search_pre_hire_request import *
from .transit_task_pre_hire_request_body import *
from .transit_task_pre_hire_request import *
from .withdraw_onboarding_pre_hire_request_body import *
from .withdraw_onboarding_pre_hire_request import *
from .enable_disable_assessment_probation_request_body import *
from .enable_disable_assessment_probation_request import *
from .search_probation_request_body import *
from .search_probation_request import *
from .submit_probation_request_body import *
from .submit_probation_request import *
from .withdraw_probation_request_body import *
from .withdraw_probation_request import *
from .create_probation_assessment_request_body import *
from .create_probation_assessment_request import *
from .delete_probation_assessment_request import *
from .patch_probation_assessment_request import *
from .get_process_request import *
from .list_process_request import *
from .update_process_approver_request import *
from .update_process_extra_request import *
from .get_process_form_variable_data_request import *
from .update_process_transfer_request import *
from .update_process_revoke_request import *
from .update_process_withdraw_request import *
from .batch_delete_report_detail_row_request import *
from .batch_save_report_detail_row_request import *
from .list_workforce_plan_request import *
from .batch_workforce_plan_detail_request_body import *
from .batch_workforce_plan_detail_request import *
from .batch_v2_workforce_plan_detail_request_body import *
from .batch_v2_workforce_plan_detail_request import *
from .batch_delete_workforce_plan_detail_row_request import *
from .batch_save_workforce_plan_detail_row_request import *
from .get_approval_groups_response_body import *
from .get_approval_groups_response import *
from .open_query_department_change_list_by_ids_approval_groups_response_body import *
from .open_query_department_change_list_by_ids_approval_groups_response import *
from .open_query_job_change_list_by_ids_approval_groups_response_body import *
from .open_query_job_change_list_by_ids_approval_groups_response import *
from .list_approver_response_body import *
from .list_approver_response import *
from .search_basic_info_bank_response_body import *
from .search_basic_info_bank_response import *
from .search_basic_info_bank_branch_response_body import *
from .search_basic_info_bank_branch_response import *
from .search_basic_info_city_response_body import *
from .search_basic_info_city_response import *
from .search_basic_info_country_region_response_body import *
from .search_basic_info_country_region_response import *
from .search_basic_info_country_region_subdivision_response_body import *
from .search_basic_info_country_region_subdivision_response import *
from .search_basic_info_currency_response_body import *
from .search_basic_info_currency_response import *
from .search_basic_info_district_response_body import *
from .search_basic_info_district_response import *
from .search_basic_info_language_response_body import *
from .search_basic_info_language_response import *
from .search_basic_info_nationality_response_body import *
from .search_basic_info_nationality_response import *
from .search_basic_info_time_zone_response_body import *
from .search_basic_info_time_zone_response import *
from .get_by_department_bp_response_body import *
from .get_by_department_bp_response import *
from .list_bp_response_body import *
from .list_bp_response import *
from .active_company_response import *
from .batch_get_company_response_body import *
from .batch_get_company_response import *
from .query_recent_change_company_response_body import *
from .query_recent_change_company_response import *
from .search_contract_response_body import *
from .search_contract_response import *
from .create_cost_center_response_body import *
from .create_cost_center_response import *
from .delete_cost_center_response import *
from .patch_cost_center_response_body import *
from .patch_cost_center_response import *
from .query_recent_change_cost_center_response_body import *
from .query_recent_change_cost_center_response import *
from .search_cost_center_response_body import *
from .search_cost_center_response import *
from .create_cost_center_version_response_body import *
from .create_cost_center_version_response import *
from .delete_cost_center_version_response import *
from .patch_cost_center_version_response_body import *
from .patch_cost_center_version_response import *
from .batch_get_department_response_body import *
from .batch_get_department_response import *
from .delete_department_response import *
from .parents_department_response_body import *
from .parents_department_response import *
from .patch_department_response import *
from .query_multi_timeline_department_response_body import *
from .query_multi_timeline_department_response import *
from .query_operation_logs_department_response_body import *
from .query_operation_logs_department_response import *
from .query_recent_change_department_response_body import *
from .query_recent_change_department_response import *
from .query_timeline_department_response_body import *
from .query_timeline_department_response import *
from .search_department_response_body import *
from .search_department_response import *
from .tree_department_response_body import *
from .tree_department_response import *
from .batch_get_employee_response_body import *
from .batch_get_employee_response import *
from .create_employee_response_body import *
from .create_employee_response import *
from .search_employee_response_body import *
from .search_employee_response import *
from .batch_employees_additional_job_response_body import *
from .batch_employees_additional_job_response import *
from .create_employees_additional_job_response_body import *
from .create_employees_additional_job_response import *
from .delete_employees_additional_job_response import *
from .patch_employees_additional_job_response_body import *
from .patch_employees_additional_job_response import *
from .batch_get_employees_bp_response_body import *
from .batch_get_employees_bp_response import *
from .batch_get_employees_job_data_response_body import *
from .batch_get_employees_job_data_response import *
from .query_employees_job_data_response_body import *
from .query_employees_job_data_response import *
from .search_enum_response_body import *
from .search_enum_response import *
from .get_job_response_body import *
from .get_job_response import *
from .list_job_response_body import *
from .list_job_response import *
from .create_job_change_response_body import *
from .create_job_change_response import *
from .revoke_job_change_response_body import *
from .revoke_job_change_response import *
from .search_job_change_response_body import *
from .search_job_change_response import *
from .batch_get_job_family_response_body import *
from .batch_get_job_family_response import *
from .query_recent_change_job_family_response_body import *
from .query_recent_change_job_family_response import *
from .create_job_grade_response_body import *
from .create_job_grade_response import *
from .delete_job_grade_response import *
from .patch_job_grade_response import *
from .query_job_grade_response_body import *
from .query_job_grade_response import *
from .query_recent_change_job_grade_response_body import *
from .query_recent_change_job_grade_response import *
from .batch_get_job_level_response_body import *
from .batch_get_job_level_response import *
from .query_recent_change_job_level_response_body import *
from .query_recent_change_job_level_response import *
from .active_location_response import *
from .batch_get_location_response_body import *
from .batch_get_location_response import *
from .patch_location_response import *
from .query_recent_change_location_response_body import *
from .query_recent_change_location_response import *
from .create_location_address_response_body import *
from .create_location_address_response import *
from .delete_location_address_response import *
from .patch_location_address_response import *
from .edit_offboarding_response_body import *
from .edit_offboarding_response import *
from .revoke_offboarding_response import *
from .submit_v2_offboarding_response_body import *
from .submit_v2_offboarding_response import *
from .create_person_response_body import *
from .create_person_response import *
from .patch_person_response_body import *
from .patch_person_response import *
from .complete_pre_hire_response_body import *
from .complete_pre_hire_response import *
from .create_pre_hire_response_body import *
from .create_pre_hire_response import *
from .delete_pre_hire_response import *
from .patch_pre_hire_response_body import *
from .patch_pre_hire_response import *
from .query_pre_hire_response_body import *
from .query_pre_hire_response import *
from .restore_flow_instance_pre_hire_response_body import *
from .restore_flow_instance_pre_hire_response import *
from .search_pre_hire_response_body import *
from .search_pre_hire_response import *
from .transit_task_pre_hire_response_body import *
from .transit_task_pre_hire_response import *
from .withdraw_onboarding_pre_hire_response_body import *
from .withdraw_onboarding_pre_hire_response import *
from .enable_disable_assessment_probation_response import *
from .search_probation_response_body import *
from .search_probation_response import *
from .submit_probation_response_body import *
from .submit_probation_response import *
from .withdraw_probation_response import *
from .create_probation_assessment_response_body import *
from .create_probation_assessment_response import *
from .delete_probation_assessment_response import *
from .patch_probation_assessment_response import *
from .get_process_response_body import *
from .get_process_response import *
from .list_process_response_body import *
from .list_process_response import *
from .update_process_approver_response_body import *
from .update_process_approver_response import *
from .update_process_extra_response import *
from .get_process_form_variable_data_response_body import *
from .get_process_form_variable_data_response import *
from .update_process_transfer_response import *
from .update_process_revoke_response import *
from .update_process_withdraw_response import *
from .batch_delete_report_detail_row_response import *
from .batch_save_report_detail_row_response import *
from .list_workforce_plan_response_body import *
from .list_workforce_plan_response import *
from .batch_workforce_plan_detail_response_body import *
from .batch_workforce_plan_detail_response import *
from .batch_v2_workforce_plan_detail_response_body import *
from .batch_v2_workforce_plan_detail_response import *
from .batch_delete_workforce_plan_detail_row_response import *
from .batch_save_workforce_plan_detail_row_response import *
from .p2_corehr_approval_groups_updated_v2 import *
from .p2_corehr_company_created_v2 import *
from .p2_corehr_company_deleted_v2 import *
from .p2_corehr_company_updated_v2 import *
from .p2_corehr_cost_center_created_v2 import *
from .p2_corehr_cost_center_deleted_v2 import *
from .p2_corehr_cost_center_updated_v2 import *
from .p2_corehr_department_created_v2 import *
from .p2_corehr_department_updated_v2 import *
from .p2_corehr_employee_domain_event_v2 import *
from .p2_corehr_job_change_status_updated_v2 import *
from .p2_corehr_job_change_updated_v2 import *
from .p2_corehr_job_family_created_v2 import *
from .p2_corehr_job_family_deleted_v2 import *
from .p2_corehr_job_family_updated_v2 import *
from .p2_corehr_job_grade_created_v2 import *
from .p2_corehr_job_grade_deleted_v2 import *
from .p2_corehr_job_grade_updated_v2 import *
from .p2_corehr_job_level_created_v2 import *
from .p2_corehr_job_level_deleted_v2 import *
from .p2_corehr_job_level_updated_v2 import *
from .p2_corehr_location_created_v2 import *
from .p2_corehr_location_deleted_v2 import *
from .p2_corehr_location_updated_v2 import *
from .p2_corehr_offboarding_checklist_updated_v2 import *
from .p2_corehr_offboarding_status_updated_v2 import *
from .p2_corehr_offboarding_updated_v2 import *
from .p2_corehr_pre_hire_onboarding_task_changed_v2 import *
from .p2_corehr_probation_updated_v2 import *
from .p2_corehr_process_updated_v2 import *
from .p2_corehr_process_approver_updated_v2 import *
from .p2_corehr_process_cc_updated_v2 import *
from .p2_corehr_process_node_updated_v2 import *
from .p2_corehr_process_status_update_v2 import *
