# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .department import Department


class BatchGetDepartmentResponseBody(object):
    _types = {
        "items": List[Department],
    }

    def __init__(self, d=None):
        self.items: Optional[List[Department]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "BatchGetDepartmentResponseBodyBuilder":
        return BatchGetDepartmentResponseBodyBuilder()


class BatchGetDepartmentResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._batch_get_department_response_body = BatchGetDepartmentResponseBody()

    def items(self, items: List[Department]) -> "BatchGetDepartmentResponseBodyBuilder":
        self._batch_get_department_response_body.items = items
        return self

    def build(self) -> "BatchGetDepartmentResponseBody":
        return self._batch_get_department_response_body
