# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class CreatePathwayResponseBody(object):
    _types = {
        "pathway_id": str,
    }

    def __init__(self, d=None):
        self.pathway_id: Optional[str] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "CreatePathwayResponseBodyBuilder":
        return CreatePathwayResponseBodyBuilder()


class CreatePathwayResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._create_pathway_response_body = CreatePathwayResponseBody()

    def pathway_id(self, pathway_id: str) -> "CreatePathwayResponseBodyBuilder":
        self._create_pathway_response_body.pathway_id = pathway_id
        return self

    def build(self) -> "CreatePathwayResponseBody":
        return self._create_pathway_response_body
