# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .custom_org_parent_info import CustomOrgParentInfo


class CustomOrgParents(object):
    _types = {
        "custom_org_id": str,
        "parent_custom_org_list": List[CustomOrgParentInfo],
    }

    def __init__(self, d=None):
        self.custom_org_id: Optional[str] = None
        self.parent_custom_org_list: Optional[List[CustomOrgParentInfo]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "CustomOrgParentsBuilder":
        return CustomOrgParentsBuilder()


class CustomOrgParentsBuilder(object):
    def __init__(self) -> None:
        self._custom_org_parents = CustomOrgParents()

    def custom_org_id(self, custom_org_id: str) -> "CustomOrgParentsBuilder":
        self._custom_org_parents.custom_org_id = custom_org_id
        return self

    def parent_custom_org_list(self, parent_custom_org_list: List[CustomOrgParentInfo]) -> "CustomOrgParentsBuilder":
        self._custom_org_parents.parent_custom_org_list = parent_custom_org_list
        return self

    def build(self) -> "CustomOrgParents":
        return self._custom_org_parents
