# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class DeleteOrgCustomOrgRequestBody(object):
    _types = {
        "org_id": str,
        "object_api_name": str,
    }

    def __init__(self, d=None):
        self.org_id: Optional[str] = None
        self.object_api_name: Optional[str] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "DeleteOrgCustomOrgRequestBodyBuilder":
        return DeleteOrgCustomOrgRequestBodyBuilder()


class DeleteOrgCustomOrgRequestBodyBuilder(object):
    def __init__(self) -> None:
        self._delete_org_custom_org_request_body = DeleteOrgCustomOrgRequestBody()

    def org_id(self, org_id: str) -> "DeleteOrgCustomOrgRequestBodyBuilder":
        self._delete_org_custom_org_request_body.org_id = org_id
        return self

    def object_api_name(self, object_api_name: str) -> "DeleteOrgCustomOrgRequestBodyBuilder":
        self._delete_org_custom_org_request_body.object_api_name = object_api_name
        return self

    def build(self) -> "DeleteOrgCustomOrgRequestBody":
        return self._delete_org_custom_org_request_body
