# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .employment_column_value_for_agent import EmploymentColumnValueForAgent


class EmploymentListForAgentRecord(object):
    _types = {
        "employment_id": str,
        "data": List[EmploymentColumnValueForAgent],
    }

    def __init__(self, d=None):
        self.employment_id: Optional[str] = None
        self.data: Optional[List[EmploymentColumnValueForAgent]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "EmploymentListForAgentRecordBuilder":
        return EmploymentListForAgentRecordBuilder()


class EmploymentListForAgentRecordBuilder(object):
    def __init__(self) -> None:
        self._employment_list_for_agent_record = EmploymentListForAgentRecord()

    def employment_id(self, employment_id: str) -> "EmploymentListForAgentRecordBuilder":
        self._employment_list_for_agent_record.employment_id = employment_id
        return self

    def data(self, data: List[EmploymentColumnValueForAgent]) -> "EmploymentListForAgentRecordBuilder":
        self._employment_list_for_agent_record.data = data
        return self

    def build(self) -> "EmploymentListForAgentRecord":
        return self._employment_list_for_agent_record
