# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.model import BaseRequest
from lark_oapi.core.enum import HttpMethod, AccessTokenType


class GetDraftRequest(BaseRequest):
    def __init__(self) -> None:
        super().__init__()
        self.user_id_type: Optional[str] = None
        self.draft_id: Optional[str] = None

    @staticmethod
    def builder() -> "GetDraftRequestBuilder":
        return GetDraftRequestBuilder()


class GetDraftRequestBuilder(object):

    def __init__(self) -> None:
        get_draft_request = GetDraftRequest()
        get_draft_request.http_method = HttpMethod.GET
        get_draft_request.uri = "/open-apis/corehr/v2/drafts/:draft_id"
        get_draft_request.token_types = {AccessTokenType.TENANT}
        self._get_draft_request: GetDraftRequest = get_draft_request

    def user_id_type(self, user_id_type: str) -> "GetDraftRequestBuilder":
        self._get_draft_request.user_id_type = user_id_type
        self._get_draft_request.add_query("user_id_type", user_id_type)
        return self

    def draft_id(self, draft_id: str) -> "GetDraftRequestBuilder":
        self._get_draft_request.draft_id = draft_id
        self._get_draft_request.paths["draft_id"] = str(draft_id)
        return self

    def build(self) -> GetDraftRequest:
        return self._get_draft_request
