# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .department_change import DepartmentChange


class OpenQueryDepartmentChangeListByIdsApprovalGroupsResponseBody(object):
    _types = {
        "department_changes": List[DepartmentChange],
    }

    def __init__(self, d=None):
        self.department_changes: Optional[List[DepartmentChange]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "OpenQueryDepartmentChangeListByIdsApprovalGroupsResponseBodyBuilder":
        return OpenQueryDepartmentChangeListByIdsApprovalGroupsResponseBodyBuilder()


class OpenQueryDepartmentChangeListByIdsApprovalGroupsResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._open_query_department_change_list_by_ids_approval_groups_response_body = OpenQueryDepartmentChangeListByIdsApprovalGroupsResponseBody()

    def department_changes(self, department_changes: List[
        DepartmentChange]) -> "OpenQueryDepartmentChangeListByIdsApprovalGroupsResponseBodyBuilder":
        self._open_query_department_change_list_by_ids_approval_groups_response_body.department_changes = department_changes
        return self

    def build(self) -> "OpenQueryDepartmentChangeListByIdsApprovalGroupsResponseBody":
        return self._open_query_department_change_list_by_ids_approval_groups_response_body
