# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class QueryRecentChangeCompanyResponseBody(object):
    _types = {
        "company_ids": List[str],
        "page_token": str,
        "has_more": bool,
        "deleted_company_ids": List[str],
    }

    def __init__(self, d=None):
        self.company_ids: Optional[List[str]] = None
        self.page_token: Optional[str] = None
        self.has_more: Optional[bool] = None
        self.deleted_company_ids: Optional[List[str]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "QueryRecentChangeCompanyResponseBodyBuilder":
        return QueryRecentChangeCompanyResponseBodyBuilder()


class QueryRecentChangeCompanyResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._query_recent_change_company_response_body = QueryRecentChangeCompanyResponseBody()

    def company_ids(self, company_ids: List[str]) -> "QueryRecentChangeCompanyResponseBodyBuilder":
        self._query_recent_change_company_response_body.company_ids = company_ids
        return self

    def page_token(self, page_token: str) -> "QueryRecentChangeCompanyResponseBodyBuilder":
        self._query_recent_change_company_response_body.page_token = page_token
        return self

    def has_more(self, has_more: bool) -> "QueryRecentChangeCompanyResponseBodyBuilder":
        self._query_recent_change_company_response_body.has_more = has_more
        return self

    def deleted_company_ids(self, deleted_company_ids: List[str]) -> "QueryRecentChangeCompanyResponseBodyBuilder":
        self._query_recent_change_company_response_body.deleted_company_ids = deleted_company_ids
        return self

    def build(self) -> "QueryRecentChangeCompanyResponseBody":
        return self._query_recent_change_company_response_body
