# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class GetJobManagerRequestBody(object):
    _types = {
    }

    def __init__(self, d=None):
        init(self, d, self._types)

    @staticmethod
    def builder() -> "GetJobManagerRequestBodyBuilder":
        return GetJobManagerRequestBodyBuilder()


class GetJobManagerRequestBodyBuilder(object):
    def __init__(self) -> None:
        self._get_job_manager_request_body = GetJobManagerRequestBody()

    def build(self) -> "GetJobManagerRequestBody":
        return self._get_job_manager_request_body
