# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .offer_approval_template import OfferApprovalTemplate


class ListOfferApprovalTemplateResponseBody(object):
    _types = {
        "has_more": bool,
        "page_token": str,
        "items": List[OfferApprovalTemplate],
    }

    def __init__(self, d=None):
        self.has_more: Optional[bool] = None
        self.page_token: Optional[str] = None
        self.items: Optional[List[OfferApprovalTemplate]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "ListOfferApprovalTemplateResponseBodyBuilder":
        return ListOfferApprovalTemplateResponseBodyBuilder()


class ListOfferApprovalTemplateResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._list_offer_approval_template_response_body = ListOfferApprovalTemplateResponseBody()

    def has_more(self, has_more: bool) -> "ListOfferApprovalTemplateResponseBodyBuilder":
        self._list_offer_approval_template_response_body.has_more = has_more
        return self

    def page_token(self, page_token: str) -> "ListOfferApprovalTemplateResponseBodyBuilder":
        self._list_offer_approval_template_response_body.page_token = page_token
        return self

    def items(self, items: List[OfferApprovalTemplate]) -> "ListOfferApprovalTemplateResponseBodyBuilder":
        self._list_offer_approval_template_response_body.items = items
        return self

    def build(self) -> "ListOfferApprovalTemplateResponseBody":
        return self._list_offer_approval_template_response_body
