# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from lark_oapi.core.model import BaseResponse
from .list_job_requirement_response_body import ListJobRequirementResponseBody


class ListJobRequirementResponse(BaseResponse):
    _types = {
        "data": ListJobRequirementResponseBody
    }

    def __init__(self, d=None):
        super().__init__(d)
        self.data: Optional[ListJobRequirementResponseBody] = None
        init(self, d, self._types)
