# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class ListInterviewFeedbackFormRequestBody(object):
    _types = {
    }

    def __init__(self, d=None):
        init(self, d, self._types)

    @staticmethod
    def builder() -> "ListInterviewFeedbackFormRequestBodyBuilder":
        return ListInterviewFeedbackFormRequestBodyBuilder()


class ListInterviewFeedbackFormRequestBodyBuilder(object):
    def __init__(self) -> None:
        self._list_interview_feedback_form_request_body = ListInterviewFeedbackFormRequestBody()

    def build(self) -> "ListInterviewFeedbackFormRequestBody":
        return self._list_interview_feedback_form_request_body
