# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class RemoveToFolderTalentResponseBody(object):
    _types = {
        "talent_id_list": List[str],
        "folder_id": str,
    }

    def __init__(self, d=None):
        self.talent_id_list: Optional[List[str]] = None
        self.folder_id: Optional[str] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "RemoveToFolderTalentResponseBodyBuilder":
        return RemoveToFolderTalentResponseBodyBuilder()


class RemoveToFolderTalentResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._remove_to_folder_talent_response_body = RemoveToFolderTalentResponseBody()

    def talent_id_list(self, talent_id_list: List[str]) -> "RemoveToFolderTalentResponseBodyBuilder":
        self._remove_to_folder_talent_response_body.talent_id_list = talent_id_list
        return self

    def folder_id(self, folder_id: str) -> "RemoveToFolderTalentResponseBodyBuilder":
        self._remove_to_folder_talent_response_body.folder_id = folder_id
        return self

    def build(self) -> "RemoveToFolderTalentResponseBody":
        return self._remove_to_folder_talent_response_body
