# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class WebsiteJobPostCustomizedTimeRange(object):
    _types = {
        "start_time": str,
        "end_time": str,
    }

    def __init__(self, d=None):
        self.start_time: Optional[str] = None
        self.end_time: Optional[str] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "WebsiteJobPostCustomizedTimeRangeBuilder":
        return WebsiteJobPostCustomizedTimeRangeBuilder()


class WebsiteJobPostCustomizedTimeRangeBuilder(object):
    def __init__(self) -> None:
        self._website_job_post_customized_time_range = WebsiteJobPostCustomizedTimeRange()

    def start_time(self, start_time: str) -> "WebsiteJobPostCustomizedTimeRangeBuilder":
        self._website_job_post_customized_time_range.start_time = start_time
        return self

    def end_time(self, end_time: str) -> "WebsiteJobPostCustomizedTimeRangeBuilder":
        self._website_job_post_customized_time_range.end_time = end_time
        return self

    def build(self) -> "WebsiteJobPostCustomizedTimeRange":
        return self._website_job_post_customized_time_range
