# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.model import BaseRequest
from lark_oapi.core.enum import HttpMethod, AccessTokenType
from .create_user_migration_request_body import CreateUserMigrationRequestBody


class CreateUserMigrationRequest(BaseRequest):
    def __init__(self) -> None:
        super().__init__()
        self.user_id_type: Optional[str] = None
        self.request_body: Optional[CreateUserMigrationRequestBody] = None

    @staticmethod
    def builder() -> "CreateUserMigrationRequestBuilder":
        return CreateUserMigrationRequestBuilder()


class CreateUserMigrationRequestBuilder(object):

    def __init__(self) -> None:
        create_user_migration_request = CreateUserMigrationRequest()
        create_user_migration_request.http_method = HttpMethod.POST
        create_user_migration_request.uri = "/open-apis/security_and_compliance/v1/user_migrations"
        create_user_migration_request.token_types = {AccessTokenType.USER, AccessTokenType.TENANT}
        self._create_user_migration_request: CreateUserMigrationRequest = create_user_migration_request

    def user_id_type(self, user_id_type: str) -> "CreateUserMigrationRequestBuilder":
        self._create_user_migration_request.user_id_type = user_id_type
        self._create_user_migration_request.add_query("user_id_type", user_id_type)
        return self

    def request_body(self, request_body: CreateUserMigrationRequestBody) -> "CreateUserMigrationRequestBuilder":
        self._create_user_migration_request.request_body = request_body
        self._create_user_migration_request.body = request_body
        return self

    def build(self) -> CreateUserMigrationRequest:
        return self._create_user_migration_request
