# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class SimpleUser(object):
    _types = {
        "id": str,
        "name": str,
    }

    def __init__(self, d=None):
        self.id: Optional[str] = None
        self.name: Optional[str] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "SimpleUserBuilder":
        return SimpleUserBuilder()


class SimpleUserBuilder(object):
    def __init__(self) -> None:
        self._simple_user = SimpleUser()

    def id(self, id: str) -> "SimpleUserBuilder":
        self._simple_user.id = id
        return self

    def name(self, name: str) -> "SimpleUserBuilder":
        self._simple_user.name = name
        return self

    def build(self) -> "SimpleUser":
        return self._simple_user
