# Code generated by Lark OpenAPI.

from .v6.resource import *


class ApplicationService(object):
    def __init__(self, config: Config) -> None:
        self.v6: V6 = V6(config)


class V6(object):
    def __init__(self, config: Config) -> None:
        self.app_recommend_rule: Optional[AppRecommendRule] = AppRecommendRule(config)
        self.application: Optional[Application] = Application(config)
        self.application_app_usage: Optional[ApplicationAppUsage] = ApplicationAppUsage(config)
        self.application_app_version: Optional[ApplicationAppVersion] = ApplicationAppVersion(config)
        self.application_feedback: Optional[ApplicationFeedback] = ApplicationFeedback(config)
        self.application_visibility: Optional[ApplicationVisibility] = ApplicationVisibility(config)
        self.bot: Optional[Bot] = Bot(config)
