# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from lark_oapi.core.model import BaseResponse
from .get_device_record_response_body import GetDeviceRecordResponseBody


class GetDeviceRecordResponse(BaseResponse):
    _types = {
        "data": GetDeviceRecordResponseBody
    }

    def __init__(self, d=None):
        super().__init__(d)
        self.data: Optional[GetDeviceRecordResponseBody] = None
        init(self, d, self._types)
