# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class MessageShareGroupChatContent(object):
    _types = {
    }

    def __init__(self, d=None):
        init(self, d, self._types)

    @staticmethod
    def builder() -> "MessageShareGroupChatContentBuilder":
        return MessageShareGroupChatContentBuilder()


class MessageShareGroupChatContentBuilder(object):
    def __init__(self) -> None:
        self._message_share_group_chat_content = MessageShareGroupChatContent()

    def build(self) -> "MessageShareGroupChatContent":
        return self._message_share_group_chat_content
