from .approval_info import *
from .area import *
from .batch_create_user_daily_shift_request import *
from .batch_create_user_daily_shift_request_body import *
from .batch_create_user_daily_shift_response import *
from .batch_create_user_daily_shift_response_body import *
from .batch_create_user_flow_request import *
from .batch_create_user_flow_request_body import *
from .batch_create_user_flow_response import *
from .batch_create_user_flow_response_body import *
from .child_field import *
from .child_item import *
from .coordinate import *
from .create_group_request import *
from .create_group_request_body import *
from .create_group_response import *
from .create_group_response_body import *
from .create_shift_request import *
from .create_shift_response import *
from .create_shift_response_body import *
from .create_user_approval_request import *
from .create_user_approval_request_body import *
from .create_user_approval_response import *
from .create_user_approval_response_body import *
from .create_user_task_remedy_request import *
from .create_user_task_remedy_response import *
from .create_user_task_remedy_response_body import *
from .delete_group_request import *
from .delete_group_response import *
from .delete_shift_request import *
from .delete_shift_response import *
from .download_file_request import *
from .download_file_response import *
from .field import *
from .file import *
from .flexible_rule import *
from .free_punch_cfg import *
from .get_group_request import *
from .get_group_response import *
from .get_group_response_body import *
from .get_leave_employ_expire_record_request import *
from .get_leave_employ_expire_record_request_body import *
from .get_leave_employ_expire_record_response import *
from .get_leave_employ_expire_record_response_body import *
from .get_shift_request import *
from .get_shift_response import *
from .get_shift_response_body import *
from .get_user_flow_request import *
from .get_user_flow_response import *
from .get_user_flow_response_body import *
from .group import *
from .group_meta import *
from .i18n_names import *
from .item import *
from .lang_text import *
from .late_off_late_on_rule import *
from .leave_accrual_record import *
from .leave_employ_expire_record import *
from .leave_need_punch_cfg import *
from .list_group_request import *
from .list_group_response import *
from .list_group_response_body import *
from .list_shift_request import *
from .list_shift_response import *
from .list_shift_response_body import *
from .location import *
from .location_info import *
from .location_info_event import *
from .location_record import *
from .location_setting import *
from .machine import *
from .member_status_change import *
from .modify_user_setting_request import *
from .modify_user_setting_request_body import *
from .modify_user_setting_response import *
from .modify_user_setting_response_body import *
from .overtime_rule import *
from .patch_leave_accrual_record_request import *
from .patch_leave_accrual_record_request_body import *
from .patch_leave_accrual_record_response import *
from .patch_leave_accrual_record_response_body import *
from .process_approval_info_request import *
from .process_approval_info_request_body import *
from .process_approval_info_response import *
from .process_approval_info_response_body import *
from .punch_member import *
from .punch_special_date_shift import *
from .punch_time_rule import *
from .query_shift_request import *
from .query_shift_response import *
from .query_shift_response_body import *
from .query_user_allowed_remedys_user_task_remedy_request import *
from .query_user_allowed_remedys_user_task_remedy_request_body import *
from .query_user_allowed_remedys_user_task_remedy_response import *
from .query_user_allowed_remedys_user_task_remedy_response_body import *
from .query_user_approval_request import *
from .query_user_approval_request_body import *
from .query_user_approval_response import *
from .query_user_approval_response_body import *
from .query_user_daily_shift_request import *
from .query_user_daily_shift_request_body import *
from .query_user_daily_shift_response import *
from .query_user_daily_shift_response_body import *
from .query_user_flow_request import *
from .query_user_flow_request_body import *
from .query_user_flow_response import *
from .query_user_flow_response_body import *
from .query_user_setting_request import *
from .query_user_setting_request_body import *
from .query_user_setting_response import *
from .query_user_setting_response_body import *
from .query_user_stats_data_request import *
from .query_user_stats_data_request_body import *
from .query_user_stats_data_response import *
from .query_user_stats_data_response_body import *
from .query_user_stats_field_request import *
from .query_user_stats_field_request_body import *
from .query_user_stats_field_response import *
from .query_user_stats_field_response_body import *
from .query_user_stats_view_request import *
from .query_user_stats_view_request_body import *
from .query_user_stats_view_response import *
from .query_user_stats_view_response_body import *
from .query_user_task_remedy_request import *
from .query_user_task_remedy_request_body import *
from .query_user_task_remedy_response import *
from .query_user_task_remedy_response_body import *
from .query_user_task_request import *
from .query_user_task_request_body import *
from .query_user_task_response import *
from .query_user_task_response_body import *
from .rest_rule import *
from .scan_wifi_info import *
from .schedule import *
from .scope_group import *
from .scope_value import *
from .search_group_request import *
from .search_group_request_body import *
from .search_group_response import *
from .search_group_response_body import *
from .shift import *
from .status_change import *
from .task_result import *
from .update_user_stats_view_request import *
from .update_user_stats_view_request_body import *
from .update_user_stats_view_response import *
from .update_user_stats_view_response_body import *
from .upload_file_request import *
from .upload_file_request_body import *
from .upload_file_response import *
from .upload_file_response_body import *
from .user_allowed_remedy import *
from .user_approval import *
from .user_daily_shift import *
from .user_flow import *
from .user_id import *
from .user_leave import *
from .user_out import *
from .user_overtime_work import *
from .user_setting import *
from .user_stats_data import *
from .user_stats_data_cell import *
from .user_stats_data_feature import *
from .user_stats_field import *
from .user_stats_view import *
from .user_task import *
from .user_task_remedy import *
from .user_trip import *
from .wifi_info import *
from .wifi_info_event import *
