# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from lark_oapi.core.model import BaseResponse
from .list_file_like_response_body import ListFileLikeResponseBody


class ListFileLikeResponse(BaseResponse):
    _types = {
        "data": ListFileLikeResponseBody
    }

    def __init__(self, d=None):
        super().__init__(d)
        self.data: Optional[ListFileLikeResponseBody] = None
        init(self, d, self._types)
