# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class CheckAgentAgentVisibilityRequestBody(object):
    _types = {
        "channel_type": str,
    }

    def __init__(self, d=None):
        self.channel_type: Optional[str] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "CheckAgentAgentVisibilityRequestBodyBuilder":
        return CheckAgentAgentVisibilityRequestBodyBuilder()


class CheckAgentAgentVisibilityRequestBodyBuilder(object):
    def __init__(self) -> None:
        self._check_agent_agent_visibility_request_body = (
            CheckAgentAgentVisibilityRequestBody()
        )

    def channel_type(
        self, channel_type: str
    ) -> "CheckAgentAgentVisibilityRequestBodyBuilder":
        self._check_agent_agent_visibility_request_body.channel_type = channel_type
        return self

    def build(self) -> "CheckAgentAgentVisibilityRequestBody":
        return self._check_agent_agent_visibility_request_body
