# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .app_stat import AppStat


class ListTenantAppStatResponseBody(object):
    _types = {
        "items": List[AppStat],
        "page_token": str,
        "has_more": bool,
    }

    def __init__(self, d=None):
        self.items: Optional[List[AppStat]] = None
        self.page_token: Optional[str] = None
        self.has_more: Optional[bool] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "ListTenantAppStatResponseBodyBuilder":
        return ListTenantAppStatResponseBodyBuilder()


class ListTenantAppStatResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._list_tenant_app_stat_response_body = ListTenantAppStatResponseBody()

    def items(self, items: List[AppStat]) -> "ListTenantAppStatResponseBodyBuilder":
        self._list_tenant_app_stat_response_body.items = items
        return self

    def page_token(self, page_token: str) -> "ListTenantAppStatResponseBodyBuilder":
        self._list_tenant_app_stat_response_body.page_token = page_token
        return self

    def has_more(self, has_more: bool) -> "ListTenantAppStatResponseBodyBuilder":
        self._list_tenant_app_stat_response_body.has_more = has_more
        return self

    def build(self) -> "ListTenantAppStatResponseBody":
        return self._list_tenant_app_stat_response_body
