# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .reaction_count import ReactionCount


class SuccessMsgReactionCount(object):
    _types = {
        "message_id": str,
        "reaction_count": List[ReactionCount],
    }

    def __init__(self, d=None):
        self.message_id: Optional[str] = None
        self.reaction_count: Optional[List[ReactionCount]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "SuccessMsgReactionCountBuilder":
        return SuccessMsgReactionCountBuilder()


class SuccessMsgReactionCountBuilder(object):
    def __init__(self) -> None:
        self._success_msg_reaction_count = SuccessMsgReactionCount()

    def message_id(self, message_id: str) -> "SuccessMsgReactionCountBuilder":
        self._success_msg_reaction_count.message_id = message_id
        return self

    def reaction_count(self, reaction_count: List[ReactionCount]) -> "SuccessMsgReactionCountBuilder":
        self._success_msg_reaction_count.reaction_count = reaction_count
        return self

    def build(self) -> "SuccessMsgReactionCount":
        return self._success_msg_reaction_count
