# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class StageTaskStatusNum(object):
    _types = {
        "task_option_id": int,
        "stage_num": int,
    }

    def __init__(self, d=None):
        self.task_option_id: Optional[int] = None
        self.stage_num: Optional[int] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "StageTaskStatusNumBuilder":
        return StageTaskStatusNumBuilder()


class StageTaskStatusNumBuilder(object):
    def __init__(self) -> None:
        self._stage_task_status_num = StageTaskStatusNum()

    def task_option_id(self, task_option_id: int) -> "StageTaskStatusNumBuilder":
        self._stage_task_status_num.task_option_id = task_option_id
        return self

    def stage_num(self, stage_num: int) -> "StageTaskStatusNumBuilder":
        self._stage_task_status_num.stage_num = stage_num
        return self

    def build(self) -> "StageTaskStatusNum":
        return self._stage_task_status_num
