from .department_id import *
from .minute import *
from .statictics import *
from .user_view_detail import *
from .get_minute_request import *
from .get_minute_media_request import *
from .get_minute_statistics_request import *
from .get_minute_transcript_request import *
from .get_minute_response_body import *
from .get_minute_response import *
from .get_minute_media_response_body import *
from .get_minute_media_response import *
from .get_minute_statistics_response_body import *
from .get_minute_statistics_response import *
from .get_minute_transcript_response import *
