# Code generated by Lark OpenAPI.

import lark_oapi as lark
from lark_oapi.api.compensation.v1 import *


def main():
    # 创建client
    client = lark.Client.builder() \
        .app_id(lark.APP_ID) \
        .app_secret(lark.APP_SECRET) \
        .log_level(lark.LogLevel.DEBUG) \
        .build()

    # 构造请求对象
    request: QueryLumpSumPaymentRequest = QueryLumpSumPaymentRequest.builder() \
        .page_size(int) \
        .page_token("str") \
        .user_id_type("open_id") \
        .request_body(QueryLumpSumPaymentRequestBody.builder()
                      .ids([])
                      .unique_ids([])
                      .user_ids([])
                      .item_ids([])
                      .create_time_gte("2023-04-01 12:34:56")
                      .create_time_lte("2023-04-01 12:34:56")
                      .modify_time_gte("2023-04-01 12:34:56")
                      .modify_time_lte("2023-04-01 12:34:56")
                      .company_ids([])
                      .service_company_ids([])
                      .department_ids([])
                      .job_family_ids([])
                      .job_level_ids([])
                      .work_location_ids([])
                      .employee_type_ids([])
                      .onboard_date_gte("2023-04-01")
                      .onboard_date_lte("2023-04-01")
                      .offboard_date_gte("2023-04-01")
                      .offboard_date_lte("2023-04-01")
                      .build()) \
        .build()

    # 发起请求
    response: QueryLumpSumPaymentResponse = client.compensation.v1.lump_sum_payment.query(request)

    # 处理失败返回
    if not response.success():
        lark.logger.error(
            f"client.compensation.v1.lump_sum_payment.query failed, code: {response.code}, msg: {response.msg}, log_id: {response.get_log_id()}")
        return

    # 处理业务结果
    lark.logger.info(lark.JSON.marshal(response.data, indent=4))


# 异步方式
async def amain():
    # 创建client
    client = lark.Client.builder() \
        .app_id(lark.APP_ID) \
        .app_secret(lark.APP_SECRET) \
        .log_level(lark.LogLevel.DEBUG) \
        .build()

    # 构造请求对象
    request: QueryLumpSumPaymentRequest = QueryLumpSumPaymentRequest.builder() \
        .page_size(int) \
        .page_token("str") \
        .user_id_type("open_id") \
        .request_body(QueryLumpSumPaymentRequestBody.builder()
                      .ids([])
                      .unique_ids([])
                      .user_ids([])
                      .item_ids([])
                      .create_time_gte("2023-04-01 12:34:56")
                      .create_time_lte("2023-04-01 12:34:56")
                      .modify_time_gte("2023-04-01 12:34:56")
                      .modify_time_lte("2023-04-01 12:34:56")
                      .company_ids([])
                      .service_company_ids([])
                      .department_ids([])
                      .job_family_ids([])
                      .job_level_ids([])
                      .work_location_ids([])
                      .employee_type_ids([])
                      .onboard_date_gte("2023-04-01")
                      .onboard_date_lte("2023-04-01")
                      .offboard_date_gte("2023-04-01")
                      .offboard_date_lte("2023-04-01")
                      .build()) \
        .build()

    # 发起请求
    response: QueryLumpSumPaymentResponse = await client.compensation.v1.lump_sum_payment.aquery(request)

    # 处理失败返回
    if not response.success():
        lark.logger.error(
            f"client.compensation.v1.lump_sum_payment.aquery failed, code: {response.code}, msg: {response.msg}, log_id: {response.get_log_id()}")
        return

    # 处理业务结果
    lark.logger.info(lark.JSON.marshal(response.data, indent=4))


if __name__ == "__main__":
    # asyncio.run(amain()) 异步方式
    main()
