from .avatar import *
from .department_id import *
from .product_i18n_name import *
from .tenant import *
from .tenant_assign_info import *
from .query_tenant_request import *
from .query_tenant_product_assign_info_request import *
from .query_tenant_response_body import *
from .query_tenant_response import *
from .query_tenant_product_assign_info_response_body import *
from .query_tenant_product_assign_info_response import *
