# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class SocialPlanCondition(object):
    _types = {
        "left_type": int,
        "operator": int,
        "right_values": List[str],
    }

    def __init__(self, d=None):
        self.left_type: Optional[int] = None
        self.operator: Optional[int] = None
        self.right_values: Optional[List[str]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "SocialPlanConditionBuilder":
        return SocialPlanConditionBuilder()


class SocialPlanConditionBuilder(object):
    def __init__(self) -> None:
        self._social_plan_condition = SocialPlanCondition()

    def left_type(self, left_type: int) -> "SocialPlanConditionBuilder":
        self._social_plan_condition.left_type = left_type
        return self

    def operator(self, operator: int) -> "SocialPlanConditionBuilder":
        self._social_plan_condition.operator = operator
        return self

    def right_values(self, right_values: List[str]) -> "SocialPlanConditionBuilder":
        self._social_plan_condition.right_values = right_values
        return self

    def build(self) -> "SocialPlanCondition":
        return self._social_plan_condition
