GEN_ENDPOINT_URI = "/callback/ws/endpoint"
DEVICE_ID = "device_id"
SERVICE_ID = "service_id"

# ErrorCode
OK = 0
SYSTEM_BUSY = 1
FORBIDDEN = 403
AUTH_FAILED = 514
INTERNAL_ERROR = 1000040343
NO_CREDENTIAL = 1000040344
EXCEED_CONN_LIMIT = 1000040350

# Header
HEADER_TYPE = "type"
HEADER_MESSAGE_ID = "message_id"
HEADER_SUM = "sum"
HEADER_SEQ = "seq"
HEADER_TRACE_ID = "trace_id"
HEADER_BIZ_RT = "biz_rt"
HEADER_HANDSHAKE_STATUS = "handshake-status"
HEADER_HANDSHAKE_MSG = "handshake-msg"
HEADER_HANDSHAKE_AUTH_ERRCODE = "handshake-autherrcode"
