# Code generated by Lark OpenAPI.

import lark_oapi as lark
from lark_oapi.api.minutes.v1 import *


def main():
    # 创建client
    client = lark.Client.builder() \
        .app_id(lark.APP_ID) \
        .app_secret(lark.APP_SECRET) \
        .log_level(lark.LogLevel.DEBUG) \
        .build()

    # 构造请求对象
    request: GetMinuteTranscriptRequest = GetMinuteTranscriptRequest.builder() \
        .minute_token("obcnq3b9jl72l83w4f149w9c") \
        .need_speaker(True) \
        .need_timestamp(True) \
        .file_format("txt；srt") \
        .build()

    # 发起请求
    response: GetMinuteTranscriptResponse = client.minutes.v1.minute_transcript.get(request)

    # 处理失败返回
    if not response.success():
        lark.logger.error(
            f"client.minutes.v1.minute_transcript.get failed, code: {response.code}, msg: {response.msg}, log_id: {response.get_log_id()}")
        return

    # 处理业务结果
    f = open(f"/file_path/{response.file_name}", "wb")
    f.write(response.file.read())
    f.close()


# 异步方式
async def amain():
    # 创建client
    client = lark.Client.builder() \
        .app_id(lark.APP_ID) \
        .app_secret(lark.APP_SECRET) \
        .log_level(lark.LogLevel.DEBUG) \
        .build()

    # 构造请求对象
    request: GetMinuteTranscriptRequest = GetMinuteTranscriptRequest.builder() \
        .minute_token("obcnq3b9jl72l83w4f149w9c") \
        .need_speaker(True) \
        .need_timestamp(True) \
        .file_format("txt；srt") \
        .build()

    # 发起请求
    response: GetMinuteTranscriptResponse = await client.minutes.v1.minute_transcript.aget(request)

    # 处理失败返回
    if not response.success():
        lark.logger.error(
            f"client.minutes.v1.minute_transcript.aget failed, code: {response.code}, msg: {response.msg}, log_id: {response.get_log_id()}")
        return

    # 处理业务结果
    f = open(f"/file_path/{response.file_name}", "wb")
    f.write(response.file.read())
    f.close()


if __name__ == "__main__":
    # asyncio.run(amain()) 异步方式
    main()
