# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class UnsubscribeApprovalRequestBody(object):
    _types = {
    }

    def __init__(self, d=None):
        init(self, d, self._types)

    @staticmethod
    def builder() -> "UnsubscribeApprovalRequestBodyBuilder":
        return UnsubscribeApprovalRequestBodyBuilder()


class UnsubscribeApprovalRequestBodyBuilder(object):
    def __init__(self) -> None:
        self._unsubscribe_approval_request_body = UnsubscribeApprovalRequestBody()

    def build(self) -> "UnsubscribeApprovalRequestBody":
        return self._unsubscribe_approval_request_body
