# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.model import BaseRequest
from lark_oapi.core.enum import HttpMethod, AccessTokenType
from .upload_html_code_and_release_app_request_body import UploadHtmlCodeAndReleaseAppRequestBody


class UploadHtmlCodeAndReleaseAppRequest(BaseRequest):
    def __init__(self) -> None:
        super().__init__()
        self.app_id: Optional[str] = None
        self.request_body: Optional[UploadHtmlCodeAndReleaseAppRequestBody] = None

    @staticmethod
    def builder() -> "UploadHtmlCodeAndReleaseAppRequestBuilder":
        return UploadHtmlCodeAndReleaseAppRequestBuilder()


class UploadHtmlCodeAndReleaseAppRequestBuilder(object):

    def __init__(self) -> None:
        upload_html_code_and_release_app_request = UploadHtmlCodeAndReleaseAppRequest()
        upload_html_code_and_release_app_request.http_method = HttpMethod.POST
        upload_html_code_and_release_app_request.uri = "/open-apis/spark/v1/apps/:app_id/upload_and_release_html_code"
        upload_html_code_and_release_app_request.token_types = {AccessTokenType.USER}
        self._upload_html_code_and_release_app_request: UploadHtmlCodeAndReleaseAppRequest = upload_html_code_and_release_app_request

    def app_id(self, app_id: str) -> "UploadHtmlCodeAndReleaseAppRequestBuilder":
        self._upload_html_code_and_release_app_request.app_id = app_id
        self._upload_html_code_and_release_app_request.paths["app_id"] = str(app_id)
        return self

    def request_body(self,
                     request_body: UploadHtmlCodeAndReleaseAppRequestBody) -> "UploadHtmlCodeAndReleaseAppRequestBuilder":
        self._upload_html_code_and_release_app_request.request_body = request_body
        self._upload_html_code_and_release_app_request.body = request_body
        return self

    def build(self) -> UploadHtmlCodeAndReleaseAppRequest:
        return self._upload_html_code_and_release_app_request
