# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class UploadCompleteAppStorageResponseBody(object):
    _types = {
        "file_key": str,
        "file_url": str,
        "file_name": str,
        "file_size": int,
        "mime_type": str,
    }

    def __init__(self, d=None):
        self.file_key: Optional[str] = None
        self.file_url: Optional[str] = None
        self.file_name: Optional[str] = None
        self.file_size: Optional[int] = None
        self.mime_type: Optional[str] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "UploadCompleteAppStorageResponseBodyBuilder":
        return UploadCompleteAppStorageResponseBodyBuilder()


class UploadCompleteAppStorageResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._upload_complete_app_storage_response_body = UploadCompleteAppStorageResponseBody()

    def file_key(self, file_key: str) -> "UploadCompleteAppStorageResponseBodyBuilder":
        self._upload_complete_app_storage_response_body.file_key = file_key
        return self

    def file_url(self, file_url: str) -> "UploadCompleteAppStorageResponseBodyBuilder":
        self._upload_complete_app_storage_response_body.file_url = file_url
        return self

    def file_name(self, file_name: str) -> "UploadCompleteAppStorageResponseBodyBuilder":
        self._upload_complete_app_storage_response_body.file_name = file_name
        return self

    def file_size(self, file_size: int) -> "UploadCompleteAppStorageResponseBodyBuilder":
        self._upload_complete_app_storage_response_body.file_size = file_size
        return self

    def mime_type(self, mime_type: str) -> "UploadCompleteAppStorageResponseBodyBuilder":
        self._upload_complete_app_storage_response_body.mime_type = mime_type
        return self

    def build(self) -> "UploadCompleteAppStorageResponseBody":
        return self._upload_complete_app_storage_response_body
