# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class DeleteGroupResponseBody(object):
    _types = {
    }

    def __init__(self, d=None):
        init(self, d, self._types)

    @staticmethod
    def builder() -> "DeleteGroupResponseBodyBuilder":
        return DeleteGroupResponseBodyBuilder()


class DeleteGroupResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._delete_group_response_body = DeleteGroupResponseBody()

    def build(self) -> "DeleteGroupResponseBody":
        return self._delete_group_response_body
