# Code generated by Lark OpenAPI.

from typing import *

from lark_oapi.core.construct import init
from .unit import Unit


class GetUnitResponseBody(object):
    _types = {
        "unit": Unit,
    }

    def __init__(self, d):
        self.unit: Optional[Unit] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "GetUnitResponseBodyBuilder":
        return GetUnitResponseBodyBuilder()


class GetUnitResponseBodyBuilder(object):
    def __init__(self, get_unit_response_body: GetUnitResponseBody = GetUnitResponseBody({})) -> None:
        self._get_unit_response_body: GetUnitResponseBody = get_unit_response_body

    def unit(self, unit: Unit) -> "GetUnitResponseBodyBuilder":
        self._get_unit_response_body.unit = unit
        return self

    def build(self) -> "GetUnitResponseBody":
        return self._get_unit_response_body
