# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class GetDocumentBlockRequestBody(object):
    _types = {
    }

    def __init__(self, d=None):
        init(self, d, self._types)

    @staticmethod
    def builder() -> "GetDocumentBlockRequestBodyBuilder":
        return GetDocumentBlockRequestBodyBuilder()


class GetDocumentBlockRequestBodyBuilder(object):
    def __init__(self) -> None:
        self._get_document_block_request_body = GetDocumentBlockRequestBody()

    def build(self) -> "GetDocumentBlockRequestBody":
        return self._get_document_block_request_body
