# Code generated by Lark OpenAPI.

import lark_oapi as lark
from lark_oapi.api.corehr.v2 import *


def main():
    # 创建client
    client = lark.Client.builder() \
        .app_id(lark.APP_ID) \
        .app_secret(lark.APP_SECRET) \
        .log_level(lark.LogLevel.DEBUG) \
        .build()

    # 构造请求对象
    request: CreateEmpCustomOrgEmployeeCustomOrgRequest = CreateEmpCustomOrgEmployeeCustomOrgRequest.builder() \
        .user_id_type("people_corehr_id") \
        .request_body(CreateEmpCustomOrgEmployeeCustomOrgRequestBody.builder()
                      .user_id("00067")
                      .object_api_name("custom_org_03")
                      .custom_org_with_rates([])
                      .start_reason("开放平台变更")
                      .effective_time("2024-06-01")
                      .build()) \
        .build()

    # 发起请求
    response: CreateEmpCustomOrgEmployeeCustomOrgResponse = client.corehr.v2.employee_custom_org.create_emp_custom_org(
        request)

    # 处理失败返回
    if not response.success():
        lark.logger.error(
            f"client.corehr.v2.employee_custom_org.create_emp_custom_org failed, code: {response.code}, msg: {response.msg}, log_id: {response.get_log_id()}")
        return

    # 处理业务结果
    lark.logger.info(lark.JSON.marshal(response.data, indent=4))


# 异步方式
async def amain():
    # 创建client
    client = lark.Client.builder() \
        .app_id(lark.APP_ID) \
        .app_secret(lark.APP_SECRET) \
        .log_level(lark.LogLevel.DEBUG) \
        .build()

    # 构造请求对象
    request: CreateEmpCustomOrgEmployeeCustomOrgRequest = CreateEmpCustomOrgEmployeeCustomOrgRequest.builder() \
        .user_id_type("people_corehr_id") \
        .request_body(CreateEmpCustomOrgEmployeeCustomOrgRequestBody.builder()
                      .user_id("00067")
                      .object_api_name("custom_org_03")
                      .custom_org_with_rates([])
                      .start_reason("开放平台变更")
                      .effective_time("2024-06-01")
                      .build()) \
        .build()

    # 发起请求
    response: CreateEmpCustomOrgEmployeeCustomOrgResponse = await client.corehr.v2.employee_custom_org.acreate_emp_custom_org(
        request)

    # 处理失败返回
    if not response.success():
        lark.logger.error(
            f"client.corehr.v2.employee_custom_org.acreate_emp_custom_org failed, code: {response.code}, msg: {response.msg}, log_id: {response.get_log_id()}")
        return

    # 处理业务结果
    lark.logger.info(lark.JSON.marshal(response.data, indent=4))


if __name__ == "__main__":
    # asyncio.run(amain()) 异步方式
    main()
