from .bank_card import *
from .bank_card_entity import *
from .bank_entity import *
from .bank_info import *
from .body_entity import *
from .body_info import *
from .business_entity import *
from .business_license import *
from .chinese_passport import *
from .chinese_passport_entity import *
from .currency import *
from .department_id import *
from .doc_chunk_bbox_item import *
from .doc_chunk_position import *
from .doc_chunk_result import *
from .doc_chunk_table_cell import *
from .doc_chunk_table_detail import *
from .doc_chunk_table_row import *
from .driving_entity import *
from .drving_license import *
from .extract_copy import *
from .extract_currency import *
from .extract_price import *
from .extract_term import *
from .extract_time import *
from .food_manage_entity import *
from .food_manage_license import *
from .food_produce_entity import *
from .food_produce_license import *
from .health_certificate import *
from .health_certificate_entity import *
from .hkm_mainland_travel_permit import *
from .hkm_mainland_travel_permit_entity import *
from .id_card import *
from .id_entity import *
from .image_detail import *
from .llm_config import *
from .llm_content import *
from .llm_detail import *
from .llm_message import *
from .llm_usage import *
from .recognized_entities import *
from .recognized_entity import *
from .resume import *
from .resume_award import *
from .resume_career import *
from .resume_certificate import *
from .resume_competition import *
from .resume_education import *
from .resume_language import *
from .resume_project import *
from .taxi_enitity import *
from .taxi_entity import *
from .taxi_invoice import *
from .train_entity import *
from .train_invoice import *
from .tw_mainland_travel_permit import *
from .tw_mainland_travel_permit_entity import *
from .vat_entity import *
from .vat_invoice import *
from .vehicle_entity import *
from .vehicle_invoice import *
from .vehicle_invoice_entity import *
from .vehicle_license import *
from .recognize_bank_card_request_body import *
from .recognize_bank_card_request import *
from .recognize_business_card_request_body import *
from .recognize_business_card_request import *
from .recognize_business_license_request_body import *
from .recognize_business_license_request import *
from .recognize_chinese_passport_request_body import *
from .recognize_chinese_passport_request import *
from .field_extraction_contract_request_body import *
from .field_extraction_contract_request import *
from .recognize_driving_license_request_body import *
from .recognize_driving_license_request import *
from .recognize_food_manage_license_request_body import *
from .recognize_food_manage_license_request import *
from .recognize_food_produce_license_request_body import *
from .recognize_food_produce_license_request import *
from .recognize_health_certificate_request_body import *
from .recognize_health_certificate_request import *
from .recognize_hkm_mainland_travel_permit_request_body import *
from .recognize_hkm_mainland_travel_permit_request import *
from .recognize_id_card_request_body import *
from .recognize_id_card_request import *
from .parse_resume_request_body import *
from .parse_resume_request import *
from .recognize_taxi_invoice_request_body import *
from .recognize_taxi_invoice_request import *
from .recognize_train_invoice_request_body import *
from .recognize_train_invoice_request import *
from .recognize_tw_mainland_travel_permit_request_body import *
from .recognize_tw_mainland_travel_permit_request import *
from .recognize_vat_invoice_request_body import *
from .recognize_vat_invoice_request import *
from .recognize_vehicle_invoice_request_body import *
from .recognize_vehicle_invoice_request import *
from .recognize_vehicle_license_request_body import *
from .recognize_vehicle_license_request import *
from .recognize_bank_card_response_body import *
from .recognize_bank_card_response import *
from .recognize_business_card_response_body import *
from .recognize_business_card_response import *
from .recognize_business_license_response_body import *
from .recognize_business_license_response import *
from .recognize_chinese_passport_response_body import *
from .recognize_chinese_passport_response import *
from .field_extraction_contract_response_body import *
from .field_extraction_contract_response import *
from .recognize_driving_license_response_body import *
from .recognize_driving_license_response import *
from .recognize_food_manage_license_response_body import *
from .recognize_food_manage_license_response import *
from .recognize_food_produce_license_response_body import *
from .recognize_food_produce_license_response import *
from .recognize_health_certificate_response_body import *
from .recognize_health_certificate_response import *
from .recognize_hkm_mainland_travel_permit_response_body import *
from .recognize_hkm_mainland_travel_permit_response import *
from .recognize_id_card_response_body import *
from .recognize_id_card_response import *
from .parse_resume_response_body import *
from .parse_resume_response import *
from .recognize_taxi_invoice_response_body import *
from .recognize_taxi_invoice_response import *
from .recognize_train_invoice_response_body import *
from .recognize_train_invoice_response import *
from .recognize_tw_mainland_travel_permit_response_body import *
from .recognize_tw_mainland_travel_permit_response import *
from .recognize_vat_invoice_response_body import *
from .recognize_vat_invoice_response import *
from .recognize_vehicle_invoice_response_body import *
from .recognize_vehicle_invoice_response import *
from .recognize_vehicle_license_response_body import *
from .recognize_vehicle_license_response import *
