# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class RecognizeVehicleLicenseRequestBody(object):
    _types = {
        "file": IO[Any],
    }

    def __init__(self, d=None):
        self.file: Optional[IO[Any]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "RecognizeVehicleLicenseRequestBodyBuilder":
        return RecognizeVehicleLicenseRequestBodyBuilder()


class RecognizeVehicleLicenseRequestBodyBuilder(object):
    def __init__(self) -> None:
        self._recognize_vehicle_license_request_body = RecognizeVehicleLicenseRequestBody()

    def file(self, file: IO[Any]) -> "RecognizeVehicleLicenseRequestBodyBuilder":
        self._recognize_vehicle_license_request_body.file = file
        return self

    def build(self) -> "RecognizeVehicleLicenseRequestBody":
        return self._recognize_vehicle_license_request_body
