# Code generated by Lark OpenAPI.

from typing import Optional

from lark_oapi.core.construct import init
from lark_oapi.core.model import BaseResponse
from .patch_metric_source_table_item_response_body import PatchMetricSourceTableItemResponseBody


class PatchMetricSourceTableItemResponse(BaseResponse):
    _types = {
        "data": PatchMetricSourceTableItemResponseBody
    }

    def __init__(self, d=None):
        super().__init__(d)
        self.data: Optional[PatchMetricSourceTableItemResponseBody] = None
        init(self, d, self._types)
