# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .okr_review import OkrReview


class QueryReviewResponseBody(object):
    _types = {
        "review_list": List[OkrReview],
    }

    def __init__(self, d=None):
        self.review_list: Optional[List[OkrReview]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "QueryReviewResponseBodyBuilder":
        return QueryReviewResponseBodyBuilder()


class QueryReviewResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._query_review_response_body = QueryReviewResponseBody()

    def review_list(self, review_list: List[OkrReview]) -> "QueryReviewResponseBodyBuilder":
        self._query_review_response_body.review_list = review_list
        return self

    def build(self) -> "QueryReviewResponseBody":
        return self._query_review_response_body
