from .department_id import *
from .file_config import *
from .speech import *
from .stream_config import *
from .file_recognize_speech_request_body import *
from .file_recognize_speech_request import *
from .stream_recognize_speech_request_body import *
from .stream_recognize_speech_request import *
from .file_recognize_speech_response_body import *
from .file_recognize_speech_response import *
from .stream_recognize_speech_response_body import *
from .stream_recognize_speech_response import *
