from .address import *
from .application_info import *
from .assigned_organization import *
from .assigned_organization_with_code import *
from .attachment_field_setting import *
from .background_check import *
from .background_check_city import *
from .background_check_country import *
from .background_check_report_object import *
from .background_check_target import *
from .bank_account import *
from .batch_check_form_instance_i18n_result import *
from .bp_role_organization import *
from .bpm_dataengine_i18n import *
from .bpm_form_error_message import *
from .calculated_field_setting import *
from .calendar_date_by_date_filter import *
from .common_schema_config import *
from .common_schema_option import *
from .company import *
from .contract import *
from .cost_center import *
from .cost_center_query import *
from .country_region import *
from .cpst_band_width import *
from .cpst_currency import *
from .cpst_grade import *
from .cpst_grade_standard_value import *
from .cpst_i18n import *
from .cpst_match_item import *
from .cpst_standard_type import *
from .currency import *
from .custom_field import *
from .custom_field_data import *
from .custom_name import *
from .date_time_field_setting import *
from .department import *
from .department_create import *
from .department_id import *
from .dependent import *
from .dimension_value import *
from .education import *
from .email import *
from .emergency_contact import *
from .employee_date_type import *
from .employee_type import *
from .employment import *
from .employment_cost_center import *
from .employment_create import *
from .employment_leave_balance import *
from .enum import *
from .enum_field_option import *
from .enum_field_setting import *
from .file import *
from .filter_condition import *
from .filter_expression import *
from .filter_rule_value import *
from .form_field_variable import *
from .form_field_variable_bool_value import *
from .form_field_variable_date_value import *
from .form_field_variable_datetime_value import *
from .form_field_variable_department_value import *
from .form_field_variable_employment_value import *
from .form_field_variable_enum_value import *
from .form_field_variable_file_value import *
from .form_field_variable_i18n_value import *
from .form_field_variable_list_object import *
from .form_field_variable_list_value import *
from .form_field_variable_null_value import *
from .form_field_variable_number_value import *
from .form_field_variable_object_value import *
from .form_field_variable_record_value import *
from .form_field_variable_record_value_example import *
from .form_field_variable_text_value import *
from .form_variable_data import *
from .form_variable_value_info import *
from .form_variable_value_info_example import *
from .hiberarchy_common import *
from .hrbp import *
from .i18n import *
from .id_info import *
from .image_field_setting import *
from .job import *
from .job_category import *
from .job_change import *
from .job_data import *
from .job_data_cost_center import *
from .job_family import *
from .job_level import *
from .leave_balance import *
from .leave_duration import *
from .leave_granting_record import *
from .leave_process_info import *
from .leave_request import *
from .leave_request_created import *
from .leave_request_created_error_message import *
from .leave_request_created_result import *
from .leave_request_detail import *
from .leave_subtype import *
from .leave_time import *
from .leave_type import *
from .location import *
from .lookup_field_setting import *
from .manage_relation import *
from .management_scope import *
from .name import *
from .national_id import *
from .national_id_type import *
from .number_field_setting import *
from .object import *
from .object_data import *
from .object_field_data import *
from .offboarding import *
from .offboarding_checklist import *
from .offboarding_data import *
from .offboarding_info import *
from .offboarding_reason import *
from .operation_log_entity import *
from .operation_log_entity_field import *
from .operation_log_list_req import *
from .operation_log_list_resp_item import *
from .org_truncation import *
from .permission_detail import *
from .permission_security_group import *
from .person import *
from .person_info_chn import *
from .person_info_mys import *
from .person_name import *
from .personal_profile import *
from .phone import *
from .phone_number_and_area_code import *
from .pre_hire import *
from .pre_hire_query import *
from .previous_employer import *
from .process import *
from .reference_object import *
from .resident_tax import *
from .role_authorization import *
from .rule_dimension import *
from .security_group import *
from .sort_option import *
from .subdivision import *
from .subregion import *
from .support_cost_center_item import *
from .temp import *
from .text_field_setting import *
from .tranfer_employment_info import *
from .transfer_info import *
from .transfer_reason import *
from .transfer_type import *
from .user_id import *
from .wk_calendar_date import *
from .wk_calendar_i18n import *
from .wk_option import *
from .work_calendar_detail import *
from .work_calendar_filter import *
from .work_experience import *
from .working_hours_type import *
from .search_assigned_user_request_body import *
from .search_assigned_user_request import *
from .add_role_assign_authorization_request_body import *
from .add_role_assign_authorization_request import *
from .get_by_param_authorization_request import *
from .query_authorization_request import *
from .remove_role_assign_authorization_request import *
from .update_role_assign_authorization_request_body import *
from .update_role_assign_authorization_request import *
from .convert_common_data_id_request_body import *
from .convert_common_data_id_request import *
from .add_enum_option_common_data_meta_data_request_body import *
from .add_enum_option_common_data_meta_data_request import *
from .edit_enum_option_common_data_meta_data_request_body import *
from .edit_enum_option_common_data_meta_data_request import *
from .create_company_request import *
from .delete_company_request import *
from .get_company_request import *
from .list_company_request import *
from .patch_company_request import *
from .match_compensation_standard_request import *
from .create_contract_request import *
from .delete_contract_request import *
from .get_contract_request import *
from .list_contract_request import *
from .patch_contract_request import *
from .get_country_region_request import *
from .list_country_region_request import *
from .get_currency_request import *
from .list_currency_request import *
from .get_by_param_custom_field_request import *
from .list_object_api_name_custom_field_request import *
from .query_custom_field_request import *
from .create_department_request import *
from .delete_department_request import *
from .get_department_request import *
from .list_department_request import *
from .patch_department_request import *
from .create_employee_type_request import *
from .delete_employee_type_request import *
from .get_employee_type_request import *
from .list_employee_type_request import *
from .patch_employee_type_request import *
from .create_employment_request import *
from .delete_employment_request import *
from .patch_employment_request import *
from .get_file_request import *
from .create_job_request import *
from .delete_job_request import *
from .get_job_request import *
from .list_job_request import *
from .patch_job_request import *
from .create_job_change_request_body import *
from .create_job_change_request import *
from .create_job_data_request import *
from .delete_job_data_request import *
from .get_job_data_request import *
from .list_job_data_request import *
from .patch_job_data_request import *
from .create_job_family_request import *
from .delete_job_family_request import *
from .get_job_family_request import *
from .list_job_family_request import *
from .patch_job_family_request import *
from .create_job_level_request import *
from .delete_job_level_request import *
from .get_job_level_request import *
from .list_job_level_request import *
from .patch_job_level_request import *
from .calendar_by_scope_leave_request import *
from .leave_balances_leave_request import *
from .leave_request_history_leave_request import *
from .leave_types_leave_request import *
from .work_calendar_leave_request import *
from .work_calendar_date_leave_request import *
from .create_leave_granting_record_request_body import *
from .create_leave_granting_record_request import *
from .delete_leave_granting_record_request import *
from .create_location_request import *
from .delete_location_request import *
from .get_location_request import *
from .list_location_request import *
from .create_national_id_type_request import *
from .delete_national_id_type_request import *
from .get_national_id_type_request import *
from .list_national_id_type_request import *
from .patch_national_id_type_request import *
from .query_offboarding_request_body import *
from .query_offboarding_request import *
from .search_offboarding_request_body import *
from .search_offboarding_request import *
from .submit_offboarding_request_body import *
from .submit_offboarding_request import *
from .create_person_request import *
from .delete_person_request import *
from .get_person_request import *
from .patch_person_request import *
from .upload_person_request_body import *
from .upload_person_request import *
from .delete_pre_hire_request import *
from .get_pre_hire_request import *
from .list_pre_hire_request import *
from .patch_pre_hire_request import *
from .get_process_form_variable_data_request import *
from .list_security_group_request import *
from .query_security_group_request_body import *
from .query_security_group_request import *
from .get_subdivision_request import *
from .list_subdivision_request import *
from .get_subregion_request import *
from .list_subregion_request import *
from .query_transfer_reason_request import *
from .query_transfer_type_request import *
from .create_working_hours_type_request import *
from .delete_working_hours_type_request import *
from .get_working_hours_type_request import *
from .list_working_hours_type_request import *
from .patch_working_hours_type_request import *
from .search_assigned_user_response_body import *
from .search_assigned_user_response import *
from .add_role_assign_authorization_response_body import *
from .add_role_assign_authorization_response import *
from .get_by_param_authorization_response_body import *
from .get_by_param_authorization_response import *
from .query_authorization_response_body import *
from .query_authorization_response import *
from .remove_role_assign_authorization_response_body import *
from .remove_role_assign_authorization_response import *
from .update_role_assign_authorization_response_body import *
from .update_role_assign_authorization_response import *
from .convert_common_data_id_response_body import *
from .convert_common_data_id_response import *
from .add_enum_option_common_data_meta_data_response_body import *
from .add_enum_option_common_data_meta_data_response import *
from .edit_enum_option_common_data_meta_data_response_body import *
from .edit_enum_option_common_data_meta_data_response import *
from .create_company_response_body import *
from .create_company_response import *
from .delete_company_response import *
from .get_company_response_body import *
from .get_company_response import *
from .list_company_response_body import *
from .list_company_response import *
from .patch_company_response_body import *
from .patch_company_response import *
from .match_compensation_standard_response_body import *
from .match_compensation_standard_response import *
from .create_contract_response_body import *
from .create_contract_response import *
from .delete_contract_response import *
from .get_contract_response_body import *
from .get_contract_response import *
from .list_contract_response_body import *
from .list_contract_response import *
from .patch_contract_response_body import *
from .patch_contract_response import *
from .get_country_region_response_body import *
from .get_country_region_response import *
from .list_country_region_response_body import *
from .list_country_region_response import *
from .get_currency_response_body import *
from .get_currency_response import *
from .list_currency_response_body import *
from .list_currency_response import *
from .get_by_param_custom_field_response_body import *
from .get_by_param_custom_field_response import *
from .list_object_api_name_custom_field_response_body import *
from .list_object_api_name_custom_field_response import *
from .query_custom_field_response_body import *
from .query_custom_field_response import *
from .create_department_response_body import *
from .create_department_response import *
from .delete_department_response import *
from .get_department_response_body import *
from .get_department_response import *
from .list_department_response_body import *
from .list_department_response import *
from .patch_department_response_body import *
from .patch_department_response import *
from .create_employee_type_response_body import *
from .create_employee_type_response import *
from .delete_employee_type_response import *
from .get_employee_type_response_body import *
from .get_employee_type_response import *
from .list_employee_type_response_body import *
from .list_employee_type_response import *
from .patch_employee_type_response_body import *
from .patch_employee_type_response import *
from .create_employment_response_body import *
from .create_employment_response import *
from .delete_employment_response import *
from .patch_employment_response_body import *
from .patch_employment_response import *
from .get_file_response import *
from .create_job_response_body import *
from .create_job_response import *
from .delete_job_response import *
from .get_job_response_body import *
from .get_job_response import *
from .list_job_response_body import *
from .list_job_response import *
from .patch_job_response_body import *
from .patch_job_response import *
from .create_job_change_response_body import *
from .create_job_change_response import *
from .create_job_data_response_body import *
from .create_job_data_response import *
from .delete_job_data_response import *
from .get_job_data_response_body import *
from .get_job_data_response import *
from .list_job_data_response_body import *
from .list_job_data_response import *
from .patch_job_data_response_body import *
from .patch_job_data_response import *
from .create_job_family_response_body import *
from .create_job_family_response import *
from .delete_job_family_response import *
from .get_job_family_response_body import *
from .get_job_family_response import *
from .list_job_family_response_body import *
from .list_job_family_response import *
from .patch_job_family_response_body import *
from .patch_job_family_response import *
from .create_job_level_response_body import *
from .create_job_level_response import *
from .delete_job_level_response import *
from .get_job_level_response_body import *
from .get_job_level_response import *
from .list_job_level_response_body import *
from .list_job_level_response import *
from .patch_job_level_response_body import *
from .patch_job_level_response import *
from .calendar_by_scope_leave_response_body import *
from .calendar_by_scope_leave_response import *
from .leave_balances_leave_response_body import *
from .leave_balances_leave_response import *
from .leave_request_history_leave_response_body import *
from .leave_request_history_leave_response import *
from .leave_types_leave_response_body import *
from .leave_types_leave_response import *
from .work_calendar_leave_response_body import *
from .work_calendar_leave_response import *
from .work_calendar_date_leave_response_body import *
from .work_calendar_date_leave_response import *
from .create_leave_granting_record_response_body import *
from .create_leave_granting_record_response import *
from .delete_leave_granting_record_response import *
from .create_location_response_body import *
from .create_location_response import *
from .delete_location_response import *
from .get_location_response_body import *
from .get_location_response import *
from .list_location_response_body import *
from .list_location_response import *
from .create_national_id_type_response_body import *
from .create_national_id_type_response import *
from .delete_national_id_type_response import *
from .get_national_id_type_response_body import *
from .get_national_id_type_response import *
from .list_national_id_type_response_body import *
from .list_national_id_type_response import *
from .patch_national_id_type_response_body import *
from .patch_national_id_type_response import *
from .query_offboarding_response_body import *
from .query_offboarding_response import *
from .search_offboarding_response_body import *
from .search_offboarding_response import *
from .submit_offboarding_response_body import *
from .submit_offboarding_response import *
from .create_person_response_body import *
from .create_person_response import *
from .delete_person_response import *
from .get_person_response_body import *
from .get_person_response import *
from .patch_person_response_body import *
from .patch_person_response import *
from .upload_person_response_body import *
from .upload_person_response import *
from .delete_pre_hire_response import *
from .get_pre_hire_response_body import *
from .get_pre_hire_response import *
from .list_pre_hire_response_body import *
from .list_pre_hire_response import *
from .patch_pre_hire_response_body import *
from .patch_pre_hire_response import *
from .get_process_form_variable_data_response_body import *
from .get_process_form_variable_data_response import *
from .list_security_group_response_body import *
from .list_security_group_response import *
from .query_security_group_response_body import *
from .query_security_group_response import *
from .get_subdivision_response_body import *
from .get_subdivision_response import *
from .list_subdivision_response_body import *
from .list_subdivision_response import *
from .get_subregion_response_body import *
from .get_subregion_response import *
from .list_subregion_response_body import *
from .list_subregion_response import *
from .query_transfer_reason_response_body import *
from .query_transfer_reason_response import *
from .query_transfer_type_response_body import *
from .query_transfer_type_response import *
from .create_working_hours_type_response_body import *
from .create_working_hours_type_response import *
from .delete_working_hours_type_response import *
from .get_working_hours_type_response_body import *
from .get_working_hours_type_response import *
from .list_working_hours_type_response_body import *
from .list_working_hours_type_response import *
from .patch_working_hours_type_response_body import *
from .patch_working_hours_type_response import *
from .p2_corehr_common_data_meta_data_updated_v1 import *
from .p2_corehr_contract_created_v1 import *
from .p2_corehr_contract_deleted_v1 import *
from .p2_corehr_contract_updated_v1 import *
from .p2_corehr_department_created_v1 import *
from .p2_corehr_department_deleted_v1 import *
from .p2_corehr_department_updated_v1 import *
from .p2_corehr_employment_converted_v1 import *
from .p2_corehr_employment_created_v1 import *
from .p2_corehr_employment_deleted_v1 import *
from .p2_corehr_employment_resigned_v1 import *
from .p2_corehr_employment_updated_v1 import *
from .p2_corehr_job_created_v1 import *
from .p2_corehr_job_deleted_v1 import *
from .p2_corehr_job_updated_v1 import *
from .p2_corehr_job_change_updated_v1 import *
from .p2_corehr_job_data_changed_v1 import *
from .p2_corehr_job_data_created_v1 import *
from .p2_corehr_job_data_deleted_v1 import *
from .p2_corehr_job_data_employed_v1 import *
from .p2_corehr_job_data_updated_v1 import *
from .p2_corehr_offboarding_updated_v1 import *
from .p2_corehr_org_role_authorization_updated_v1 import *
from .p2_corehr_person_created_v1 import *
from .p2_corehr_person_deleted_v1 import *
from .p2_corehr_person_updated_v1 import *
from .p2_corehr_pre_hire_updated_v1 import *
