# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class DeleteJobResponseBody(object):
    _types = {
    }

    def __init__(self, d=None):
        init(self, d, self._types)

    @staticmethod
    def builder() -> "DeleteJobResponseBodyBuilder":
        return DeleteJobResponseBodyBuilder()


class DeleteJobResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._delete_job_response_body = DeleteJobResponseBody()

    def build(self) -> "DeleteJobResponseBody":
        return self._delete_job_response_body
