# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .currency import Currency


class GetCurrencyResponseBody(object):
    _types = {
        "currency": Currency,
    }

    def __init__(self, d=None):
        self.currency: Optional[Currency] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "GetCurrencyResponseBodyBuilder":
        return GetCurrencyResponseBodyBuilder()


class GetCurrencyResponseBodyBuilder(object):
    def __init__(self) -> None:
        self._get_currency_response_body = GetCurrencyResponseBody()

    def currency(self, currency: Currency) -> "GetCurrencyResponseBodyBuilder":
        self._get_currency_response_body.currency = currency
        return self

    def build(self) -> "GetCurrencyResponseBody":
        return self._get_currency_response_body
