# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from lark_oapi.core.model import BaseResponse
from .get_company_response_body import GetCompanyResponseBody


class GetCompanyResponse(BaseResponse):
    _types = {
        "data": GetCompanyResponseBody
    }

    def __init__(self, d=None):
        super().__init__(d)
        self.data: Optional[GetCompanyResponseBody] = None
        init(self, d, self._types)
