from .accessibility import *
from .app_ability import *
from .app_ability_bot import *
from .app_ability_bot_i18n import *
from .app_ability_web import *
from .app_admin_user import *
from .app_badge import *
from .app_collaborator import *
from .app_common_category import *
from .app_config_contacts_range import *
from .app_config_event import *
from .app_config_scope import *
from .app_config_scope_item import *
from .app_config_security import *
from .app_config_security_item import *
from .app_config_visibility import *
from .app_contacts_range_id_list import *
from .app_custom_category import *
from .app_custom_category_i18n_info import *
from .app_i18n_info import *
from .app_message_trend_item import *
from .app_recommend_rule import *
from .app_recommend_rule_item_info import *
from .app_recommend_rule_item_info_i18n_name import *
from .app_recommend_rule_visibility_info import *
from .app_scope import *
from .app_scope_i18n_info import *
from .app_scopes import *
from .app_usage_trend_items import *
from .app_version_id import *
from .app_version_remark import *
from .app_version_remark_event import *
from .app_visibility import *
from .app_visibility_event import *
from .app_visibility_id_list import *
from .app_visibility_item import *
from .app_visible_list import *
from .app_visible_list_event import *
from .application import *
from .application_app_contacts_range import *
from .application_app_usage import *
from .application_app_version import *
from .application_app_version_event import *
from .application_department_app_usage import *
from .application_event_owner import *
from .application_feedback import *
from .application_owner import *
from .application_visibility import *
from .application_visibility_department_white_black_info import *
from .application_visibility_group_white_black_info import *
from .application_visibility_user_white_black_info import *
from .block import *
from .block_i18n_info import *
from .bot import *
from .client_badge_num import *
from .cloud_doc import *
from .cloud_doc_i18n_info import *
from .department_id import *
from .docs_block import *
from .event import *
from .event_and_callback_encrypt_strategy import *
from .gadget import *
from .message_action import *
from .message_action_i18n_info import *
from .message_overview_item import *
from .miniprogram import *
from .msg_action import *
from .msg_action_i18n_info import *
from .navigate import *
from .navigate_meta import *
from .openapi_option import *
from .operator import *
from .plus_menu import *
from .scope import *
from .usage_overview_item import *
from .usage_trend_item import *
from .usage_user import *
from .user import *
from .user_id import *
from .web_app import *
from .widget import *
from .workplace_widget import *
from .set_app_badge_request import *
from .list_app_recommend_rule_request import *
from .contacts_range_configuration_application_request import *
from .get_application_request import *
from .patch_application_request import *
from .underauditlist_application_request import *
from .department_overview_application_app_usage_request_body import *
from .department_overview_application_app_usage_request import *
from .message_push_overview_application_app_usage_request_body import *
from .message_push_overview_application_app_usage_request import *
from .overview_application_app_usage_request_body import *
from .overview_application_app_usage_request import *
from .contacts_range_suggest_application_app_version_request import *
from .get_application_app_version_request import *
from .list_application_app_version_request import *
from .patch_application_app_version_request import *
from .patch_application_contacts_range_request_body import *
from .patch_application_contacts_range_request import *
from .list_application_feedback_request import *
from .patch_application_feedback_request import *
from .update_application_management_request_body import *
from .update_application_management_request import *
from .check_white_black_list_application_visibility_request_body import *
from .check_white_black_list_application_visibility_request import *
from .patch_application_visibility_request_body import *
from .patch_application_visibility_request import *
from .apply_scope_request import *
from .list_scope_request import *
from .set_app_badge_response import *
from .list_app_recommend_rule_response_body import *
from .list_app_recommend_rule_response import *
from .contacts_range_configuration_application_response_body import *
from .contacts_range_configuration_application_response import *
from .get_application_response_body import *
from .get_application_response import *
from .patch_application_response import *
from .underauditlist_application_response_body import *
from .underauditlist_application_response import *
from .department_overview_application_app_usage_response_body import *
from .department_overview_application_app_usage_response import *
from .message_push_overview_application_app_usage_response_body import *
from .message_push_overview_application_app_usage_response import *
from .overview_application_app_usage_response_body import *
from .overview_application_app_usage_response import *
from .contacts_range_suggest_application_app_version_response_body import *
from .contacts_range_suggest_application_app_version_response import *
from .get_application_app_version_response_body import *
from .get_application_app_version_response import *
from .list_application_app_version_response_body import *
from .list_application_app_version_response import *
from .patch_application_app_version_response import *
from .patch_application_contacts_range_response import *
from .list_application_feedback_response_body import *
from .list_application_feedback_response import *
from .patch_application_feedback_response import *
from .update_application_management_response import *
from .check_white_black_list_application_visibility_response_body import *
from .check_white_black_list_application_visibility_response import *
from .patch_application_visibility_response import *
from .apply_scope_response import *
from .list_scope_response_body import *
from .list_scope_response import *
from .p2_application_application_created_v6 import *
from .p2_application_application_app_version_audit_v6 import *
from .p2_application_application_app_version_publish_apply_v6 import *
from .p2_application_application_app_version_publish_revoke_v6 import *
from .p2_application_application_feedback_created_v6 import *
from .p2_application_application_feedback_updated_v6 import *
from .p2_application_application_visibility_added_v6 import *
from .p2_application_bot_menu_v6 import *
