# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .origin_source_message import OriginSourceMessage


class OriginReferResource(object):
    _types = {
        "resource_id": str,
        "type": str,
        "source_message": OriginSourceMessage,
        "unavailable_reason": str,
    }

    def __init__(self, d=None):
        self.resource_id: Optional[str] = None
        self.type: Optional[str] = None
        self.source_message: Optional[OriginSourceMessage] = None
        self.unavailable_reason: Optional[str] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "OriginReferResourceBuilder":
        return OriginReferResourceBuilder()


class OriginReferResourceBuilder(object):
    def __init__(self) -> None:
        self._origin_refer_resource = OriginReferResource()

    def resource_id(self, resource_id: str) -> "OriginReferResourceBuilder":
        self._origin_refer_resource.resource_id = resource_id
        return self

    def type(self, type: str) -> "OriginReferResourceBuilder":
        self._origin_refer_resource.type = type
        return self

    def source_message(
        self, source_message: OriginSourceMessage
    ) -> "OriginReferResourceBuilder":
        self._origin_refer_resource.source_message = source_message
        return self

    def unavailable_reason(
        self, unavailable_reason: str
    ) -> "OriginReferResourceBuilder":
        self._origin_refer_resource.unavailable_reason = unavailable_reason
        return self

    def build(self) -> "OriginReferResource":
        return self._origin_refer_resource
