from .alert import *
from .apply_reserve_request import *
from .apply_reserve_request_body import *
from .apply_reserve_response import *
from .apply_reserve_response_body import *
from .approval_config import *
from .approval_config_event import *
from .conditions import *
from .contact import *
from .create_room_level_request import *
from .create_room_level_response import *
from .create_room_level_response_body import *
from .create_room_request import *
from .create_room_response import *
from .create_room_response_body import *
from .create_scope_config_request import *
from .create_scope_config_response import *
from .custom_list import *
from .del_room_level_request import *
from .del_room_level_request_body import *
from .del_room_level_response import *
from .delete_reserve_request import *
from .delete_reserve_response import *
from .delete_room_request import *
from .delete_room_response import *
from .device import *
from .disable_inform_config import *
from .download_export_request import *
from .download_export_response import *
from .end_meeting_request import *
from .end_meeting_response import *
from .get_active_meeting_reserve_request import *
from .get_active_meeting_reserve_response import *
from .get_active_meeting_reserve_response_body import *
from .get_daily_report_request import *
from .get_daily_report_response import *
from .get_daily_report_response_body import *
from .get_export_request import *
from .get_export_response import *
from .get_export_response_body import *
from .get_meeting_list_request import *
from .get_meeting_list_response import *
from .get_meeting_list_response_body import *
from .get_meeting_recording_request import *
from .get_meeting_recording_response import *
from .get_meeting_recording_response_body import *
from .get_meeting_request import *
from .get_meeting_response import *
from .get_meeting_response_body import *
from .get_participant_list_request import *
from .get_participant_list_response import *
from .get_participant_list_response_body import *
from .get_participant_quality_list_request import *
from .get_participant_quality_list_response import *
from .get_participant_quality_list_response_body import *
from .get_reserve_config_admin_request import *
from .get_reserve_config_admin_response import *
from .get_reserve_config_admin_response_body import *
from .get_reserve_config_disable_inform_request import *
from .get_reserve_config_disable_inform_response import *
from .get_reserve_config_disable_inform_response_body import *
from .get_reserve_config_form_request import *
from .get_reserve_config_form_response import *
from .get_reserve_config_form_response_body import *
from .get_reserve_request import *
from .get_reserve_response import *
from .get_reserve_response_body import *
from .get_resource_reservation_list_request import *
from .get_resource_reservation_list_response import *
from .get_resource_reservation_list_response_body import *
from .get_room_level_request import *
from .get_room_level_response import *
from .get_room_level_response_body import *
from .get_room_request import *
from .get_room_response import *
from .get_room_response_body import *
from .get_scope_config_request import *
from .get_scope_config_response import *
from .get_scope_config_response_body import *
from .get_top_user_report_request import *
from .get_top_user_report_response import *
from .get_top_user_report_response_body import *
from .invite_meeting_request import *
from .invite_meeting_request_body import *
from .invite_meeting_response import *
from .invite_meeting_response_body import *
from .kickout_meeting_request import *
from .kickout_meeting_request_body import *
from .kickout_meeting_response import *
from .kickout_meeting_response_body import *
from .list_alert_request import *
from .list_alert_response import *
from .list_alert_response_body import *
from .list_by_no_meeting_request import *
from .list_by_no_meeting_response import *
from .list_by_no_meeting_response_body import *
from .list_room_level_request import *
from .list_room_level_response import *
from .list_room_level_response_body import *
from .list_room_request import *
from .list_room_response import *
from .list_room_response_body import *
from .material import *
from .material_delete_result import *
from .material_review_result import *
from .material_upload_result import *
from .meeting import *
from .meeting_ability import *
from .meeting_event_meeting import *
from .meeting_event_user import *
from .meeting_info import *
from .meeting_invite_status import *
from .meeting_list_export_request import *
from .meeting_list_export_request_body import *
from .meeting_list_export_response import *
from .meeting_list_export_response_body import *
from .meeting_participant import *
from .meeting_participant_result import *
from .meeting_recording import *
from .meeting_user import *
from .mget_room_level_request import *
from .mget_room_level_request_body import *
from .mget_room_level_response import *
from .mget_room_level_response_body import *
from .mget_room_request import *
from .mget_room_request_body import *
from .mget_room_response import *
from .mget_room_response_body import *
from .options import *
from .p2_vc_meeting_all_meeting_ended_v1 import *
from .p2_vc_meeting_all_meeting_started_v1 import *
from .p2_vc_meeting_join_meeting_v1 import *
from .p2_vc_meeting_leave_meeting_v1 import *
from .p2_vc_meeting_meeting_ended_v1 import *
from .p2_vc_meeting_meeting_started_v1 import *
from .p2_vc_meeting_recording_ended_v1 import *
from .p2_vc_meeting_recording_ready_v1 import *
from .p2_vc_meeting_recording_started_v1 import *
from .p2_vc_meeting_share_ended_v1 import *
from .p2_vc_meeting_share_started_v1 import *
from .p2_vc_reserve_config_updated_v1 import *
from .p2_vc_room_created_v1 import *
from .p2_vc_room_deleted_v1 import *
from .p2_vc_room_level_created_v1 import *
from .p2_vc_room_level_deleted_v1 import *
from .p2_vc_room_level_updated_v1 import *
from .p2_vc_room_updated_v1 import *
from .participant import *
from .participant_list_export_request import *
from .participant_list_export_request_body import *
from .participant_list_export_response import *
from .participant_list_export_response_body import *
from .participant_quality import *
from .participant_quality_list_export_request import *
from .participant_quality_list_export_request_body import *
from .participant_quality_list_export_response import *
from .participant_quality_list_export_response_body import *
from .patch_reserve_config_admin_request import *
from .patch_reserve_config_admin_request_body import *
from .patch_reserve_config_admin_response import *
from .patch_reserve_config_disable_inform_request import *
from .patch_reserve_config_disable_inform_request_body import *
from .patch_reserve_config_disable_inform_response import *
from .patch_reserve_config_form_request import *
from .patch_reserve_config_form_request_body import *
from .patch_reserve_config_form_response import *
from .patch_reserve_config_request import *
from .patch_reserve_config_request_body import *
from .patch_reserve_config_response import *
from .patch_room_level_request import *
from .patch_room_level_response import *
from .patch_room_request import *
from .patch_room_response import *
from .pstn_sip_info import *
from .quality_audio import *
from .quality_cpu_usage import *
from .quality_network import *
from .quality_video_sharing import *
from .query_room_config_request import *
from .query_room_config_response import *
from .query_room_config_response_body import *
from .recording_permission_object import *
from .report import *
from .report_meeting_daily import *
from .report_top_user import *
from .reserve import *
from .reserve_action_permission import *
from .reserve_admin_config import *
from .reserve_assign_host import *
from .reserve_call_setting import *
from .reserve_callee import *
from .reserve_correction_check_info import *
from .reserve_form_config import *
from .reserve_meeting_setting import *
from .reserve_permission_checker import *
from .reserve_scope_config import *
from .reserve_scope_config_event import *
from .reserve_scope_reserve_config_request import *
from .reserve_scope_reserve_config_response import *
from .reserve_scope_reserve_config_response_body import *
from .resource_reservation_list_export_request import *
from .resource_reservation_list_export_request_body import *
from .resource_reservation_list_export_response import *
from .resource_reservation_list_export_response_body import *
from .room import *
from .room_config import *
from .room_digital_signage import *
from .room_digital_signage_material import *
from .room_event import *
from .room_level import *
from .room_meeting_reservation import *
from .room_status import *
from .room_status_event import *
from .scope_config import *
from .search_room_level_request import *
from .search_room_level_response import *
from .search_room_level_response_body import *
from .search_room_request import *
from .search_room_request_body import *
from .search_room_response import *
from .search_room_response_body import *
from .set_checkboard_access_code_room_config_request import *
from .set_checkboard_access_code_room_config_request_body import *
from .set_checkboard_access_code_room_config_response import *
from .set_checkboard_access_code_room_config_response_body import *
from .set_host_meeting_request import *
from .set_host_meeting_request_body import *
from .set_host_meeting_response import *
from .set_host_meeting_response_body import *
from .set_permission_meeting_recording_request import *
from .set_permission_meeting_recording_request_body import *
from .set_permission_meeting_recording_response import *
from .set_room_access_code_room_config_request import *
from .set_room_access_code_room_config_request_body import *
from .set_room_access_code_room_config_response import *
from .set_room_access_code_room_config_response_body import *
from .set_room_config_request import *
from .set_room_config_request_body import *
from .set_room_config_response import *
from .start_meeting_recording_request import *
from .start_meeting_recording_request_body import *
from .start_meeting_recording_response import *
from .stop_meeting_recording_request import *
from .stop_meeting_recording_response import *
from .subscribe_department import *
from .subscribe_user import *
from .subscribe_user_event import *
from .time_config import *
from .update_reserve_request import *
from .update_reserve_request_body import *
from .update_reserve_response import *
from .update_reserve_response_body import *
from .user_id import *
