# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class GetParticipantQualityListRequestBody(object):
    _types = {
    }

    def __init__(self, d=None):
        init(self, d, self._types)

    @staticmethod
    def builder() -> "GetParticipantQualityListRequestBodyBuilder":
        return GetParticipantQualityListRequestBodyBuilder()


class GetParticipantQualityListRequestBodyBuilder(object):
    def __init__(self) -> None:
        self._get_participant_quality_list_request_body = GetParticipantQualityListRequestBody()

    def build(self) -> "GetParticipantQualityListRequestBody":
        return self._get_participant_quality_list_request_body
