# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.model import BaseRequest
from lark_oapi.core.enum import HttpMethod, AccessTokenType
from .unsubscription_meeting_request_body import UnsubscriptionMeetingRequestBody


class UnsubscriptionMeetingRequest(BaseRequest):
    def __init__(self) -> None:
        super().__init__()
        self.request_body: Optional[UnsubscriptionMeetingRequestBody] = None

    @staticmethod
    def builder() -> "UnsubscriptionMeetingRequestBuilder":
        return UnsubscriptionMeetingRequestBuilder()


class UnsubscriptionMeetingRequestBuilder(object):

    def __init__(self) -> None:
        unsubscription_meeting_request = UnsubscriptionMeetingRequest()
        unsubscription_meeting_request.http_method = HttpMethod.POST
        unsubscription_meeting_request.uri = "/open-apis/vc/v1/meetings/unsubscription"
        unsubscription_meeting_request.token_types = {AccessTokenType.USER}
        self._unsubscription_meeting_request: UnsubscriptionMeetingRequest = unsubscription_meeting_request

    def request_body(self, request_body: UnsubscriptionMeetingRequestBody) -> "UnsubscriptionMeetingRequestBuilder":
        self._unsubscription_meeting_request.request_body = request_body
        self._unsubscription_meeting_request.body = request_body
        return self

    def build(self) -> UnsubscriptionMeetingRequest:
        return self._unsubscription_meeting_request
