# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .payment_accounting_item import PaymentAccountingItem


class PaymentActivityDetail(object):
    _types = {
        "employee_id": str,
        "payment_details": List[PaymentAccountingItem],
    }

    def __init__(self, d=None):
        self.employee_id: Optional[str] = None
        self.payment_details: Optional[List[PaymentAccountingItem]] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "PaymentActivityDetailBuilder":
        return PaymentActivityDetailBuilder()


class PaymentActivityDetailBuilder(object):
    def __init__(self) -> None:
        self._payment_activity_detail = PaymentActivityDetail()

    def employee_id(self, employee_id: str) -> "PaymentActivityDetailBuilder":
        self._payment_activity_detail.employee_id = employee_id
        return self

    def payment_details(self, payment_details: List[PaymentAccountingItem]) -> "PaymentActivityDetailBuilder":
        self._payment_activity_detail.payment_details = payment_details
        return self

    def build(self) -> "PaymentActivityDetail":
        return self._payment_activity_detail
