from .bank_card import *
from .business_card import *
from .business_license import *
from .chinese_passport import *
from .contract import *
from .driving_license import *
from .food_manage_license import *
from .food_produce_license import *
from .health_certificate import *
from .hkm_mainland_travel_permit import *
from .id_card import *
from .resume import *
from .taxi_invoice import *
from .train_invoice import *
from .tw_mainland_travel_permit import *
from .vat_invoice import *
from .vehicle_invoice import *
from .vehicle_license import *
