# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .auth_info import AuthInfo
from .client_info import ClientInfo


class CommonHead(object):
    _types = {
        "id": str,
        "tenant_id": str,
        "app_id": str,
        "open_id": str,
        "tenant_key": str,
        "auth": AuthInfo,
        "fields": Dict[str, str],
        "env": str,
        "locale": str,
        "client": ClientInfo,
    }

    def __init__(self, d=None):
        self.id: Optional[str] = None
        self.tenant_id: Optional[str] = None
        self.app_id: Optional[str] = None
        self.open_id: Optional[str] = None
        self.tenant_key: Optional[str] = None
        self.auth: Optional[AuthInfo] = None
        self.fields: Optional[Dict[str, str]] = None
        self.env: Optional[str] = None
        self.locale: Optional[str] = None
        self.client: Optional[ClientInfo] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "CommonHeadBuilder":
        return CommonHeadBuilder()


class CommonHeadBuilder(object):
    def __init__(self) -> None:
        self._common_head = CommonHead()

    def id(self, id: str) -> "CommonHeadBuilder":
        self._common_head.id = id
        return self

    def tenant_id(self, tenant_id: str) -> "CommonHeadBuilder":
        self._common_head.tenant_id = tenant_id
        return self

    def app_id(self, app_id: str) -> "CommonHeadBuilder":
        self._common_head.app_id = app_id
        return self

    def open_id(self, open_id: str) -> "CommonHeadBuilder":
        self._common_head.open_id = open_id
        return self

    def tenant_key(self, tenant_key: str) -> "CommonHeadBuilder":
        self._common_head.tenant_key = tenant_key
        return self

    def auth(self, auth: AuthInfo) -> "CommonHeadBuilder":
        self._common_head.auth = auth
        return self

    def fields(self, fields: Dict[str, str]) -> "CommonHeadBuilder":
        self._common_head.fields = fields
        return self

    def env(self, env: str) -> "CommonHeadBuilder":
        self._common_head.env = env
        return self

    def locale(self, locale: str) -> "CommonHeadBuilder":
        self._common_head.locale = locale
        return self

    def client(self, client: ClientInfo) -> "CommonHeadBuilder":
        self._common_head.client = client
        return self

    def build(self) -> "CommonHead":
        return self._common_head
