# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from lark_oapi.event.context import EventContext
from .user_id import UserId
from .bitable_table_field_action import BitableTableFieldAction
from .user_id import UserId


class P2DriveFileBitableFieldChangedV1Data(object):
    _types = {
        "file_type": str,
        "file_token": str,
        "table_id": str,
        "operator_id": UserId,
        "action_list": List[BitableTableFieldAction],
        "revision": int,
        "subscriber_id_list": List[UserId],
        "update_time": int,
    }

    def __init__(self, d=None):
        self.file_type: Optional[str] = None
        self.file_token: Optional[str] = None
        self.table_id: Optional[str] = None
        self.operator_id: Optional[UserId] = None
        self.action_list: Optional[List[BitableTableFieldAction]] = None
        self.revision: Optional[int] = None
        self.subscriber_id_list: Optional[List[UserId]] = None
        self.update_time: Optional[int] = None
        init(self, d, self._types)


class P2DriveFileBitableFieldChangedV1(EventContext):
    _types = {
        "event": P2DriveFileBitableFieldChangedV1Data
    }

    def __init__(self, d=None):
        super().__init__(d)
        self._types.update(super()._types)
        self.event: Optional[P2DriveFileBitableFieldChangedV1Data] = None
        init(self, d, self._types)
