# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.model import BaseRequest
from lark_oapi.core.enum import HttpMethod, AccessTokenType
from .create_department_request_body import CreateDepartmentRequestBody


class CreateDepartmentRequest(BaseRequest):
    def __init__(self) -> None:
        super().__init__()
        self.employee_id_type: Optional[str] = None
        self.department_id_type: Optional[str] = None
        self.request_body: Optional[CreateDepartmentRequestBody] = None

    @staticmethod
    def builder() -> "CreateDepartmentRequestBuilder":
        return CreateDepartmentRequestBuilder()


class CreateDepartmentRequestBuilder(object):

    def __init__(self) -> None:
        create_department_request = CreateDepartmentRequest()
        create_department_request.http_method = HttpMethod.POST
        create_department_request.uri = "/open-apis/directory/v1/departments"
        create_department_request.token_types = {AccessTokenType.TENANT, AccessTokenType.USER}
        self._create_department_request: CreateDepartmentRequest = create_department_request

    def employee_id_type(self, employee_id_type: str) -> "CreateDepartmentRequestBuilder":
        self._create_department_request.employee_id_type = employee_id_type
        self._create_department_request.add_query("employee_id_type", employee_id_type)
        return self

    def department_id_type(self, department_id_type: str) -> "CreateDepartmentRequestBuilder":
        self._create_department_request.department_id_type = department_id_type
        self._create_department_request.add_query("department_id_type", department_id_type)
        return self

    def request_body(self, request_body: CreateDepartmentRequestBody) -> "CreateDepartmentRequestBuilder":
        self._create_department_request.request_body = request_body
        self._create_department_request.body = request_body
        return self

    def build(self) -> CreateDepartmentRequest:
        return self._create_department_request
