# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init
from .i18n_text import I18nText
from .i18n_text import I18nText


class JobLevel(object):
    _types = {
        "job_level_id": str,
        "tenant_id": str,
        "job_level_name": I18nText,
        "is_enabled": bool,
        "is_deleted": bool,
        "order": str,
        "description": I18nText,
        "create_time": str,
        "update_time": str,
        "creator_id": str,
        "updator_id": str,
        "external_id": str,
    }

    def __init__(self, d=None):
        self.job_level_id: Optional[str] = None
        self.tenant_id: Optional[str] = None
        self.job_level_name: Optional[I18nText] = None
        self.is_enabled: Optional[bool] = None
        self.is_deleted: Optional[bool] = None
        self.order: Optional[str] = None
        self.description: Optional[I18nText] = None
        self.create_time: Optional[str] = None
        self.update_time: Optional[str] = None
        self.creator_id: Optional[str] = None
        self.updator_id: Optional[str] = None
        self.external_id: Optional[str] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "JobLevelBuilder":
        return JobLevelBuilder()


class JobLevelBuilder(object):
    def __init__(self) -> None:
        self._job_level = JobLevel()

    def job_level_id(self, job_level_id: str) -> "JobLevelBuilder":
        self._job_level.job_level_id = job_level_id
        return self

    def tenant_id(self, tenant_id: str) -> "JobLevelBuilder":
        self._job_level.tenant_id = tenant_id
        return self

    def job_level_name(self, job_level_name: I18nText) -> "JobLevelBuilder":
        self._job_level.job_level_name = job_level_name
        return self

    def is_enabled(self, is_enabled: bool) -> "JobLevelBuilder":
        self._job_level.is_enabled = is_enabled
        return self

    def is_deleted(self, is_deleted: bool) -> "JobLevelBuilder":
        self._job_level.is_deleted = is_deleted
        return self

    def order(self, order: str) -> "JobLevelBuilder":
        self._job_level.order = order
        return self

    def description(self, description: I18nText) -> "JobLevelBuilder":
        self._job_level.description = description
        return self

    def create_time(self, create_time: str) -> "JobLevelBuilder":
        self._job_level.create_time = create_time
        return self

    def update_time(self, update_time: str) -> "JobLevelBuilder":
        self._job_level.update_time = update_time
        return self

    def creator_id(self, creator_id: str) -> "JobLevelBuilder":
        self._job_level.creator_id = creator_id
        return self

    def updator_id(self, updator_id: str) -> "JobLevelBuilder":
        self._job_level.updator_id = updator_id
        return self

    def external_id(self, external_id: str) -> "JobLevelBuilder":
        self._job_level.external_id = external_id
        return self

    def build(self) -> "JobLevel":
        return self._job_level
