# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.model import BaseRequest
from lark_oapi.core.enum import HttpMethod, AccessTokenType
from .update_collaboration_rule_request_body import UpdateCollaborationRuleRequestBody


class UpdateCollaborationRuleRequest(BaseRequest):
    def __init__(self) -> None:
        super().__init__()
        self.target_tenant_key: Optional[str] = None
        self.collaboration_rule_id: Optional[str] = None
        self.request_body: Optional[UpdateCollaborationRuleRequestBody] = None

    @staticmethod
    def builder() -> "UpdateCollaborationRuleRequestBuilder":
        return UpdateCollaborationRuleRequestBuilder()


class UpdateCollaborationRuleRequestBuilder(object):

    def __init__(self) -> None:
        update_collaboration_rule_request = UpdateCollaborationRuleRequest()
        update_collaboration_rule_request.http_method = HttpMethod.PUT
        update_collaboration_rule_request.uri = "/open-apis/directory/v1/collaboration_rules/:collaboration_rule_id"
        update_collaboration_rule_request.token_types = {AccessTokenType.USER, AccessTokenType.TENANT}
        self._update_collaboration_rule_request: UpdateCollaborationRuleRequest = update_collaboration_rule_request

    def target_tenant_key(self, target_tenant_key: str) -> "UpdateCollaborationRuleRequestBuilder":
        self._update_collaboration_rule_request.target_tenant_key = target_tenant_key
        self._update_collaboration_rule_request.add_query("target_tenant_key", target_tenant_key)
        return self

    def collaboration_rule_id(self, collaboration_rule_id: str) -> "UpdateCollaborationRuleRequestBuilder":
        self._update_collaboration_rule_request.collaboration_rule_id = collaboration_rule_id
        self._update_collaboration_rule_request.paths["collaboration_rule_id"] = str(collaboration_rule_id)
        return self

    def request_body(self, request_body: UpdateCollaborationRuleRequestBody) -> "UpdateCollaborationRuleRequestBuilder":
        self._update_collaboration_rule_request.request_body = request_body
        self._update_collaboration_rule_request.body = request_body
        return self

    def build(self) -> UpdateCollaborationRuleRequest:
        return self._update_collaboration_rule_request
