# Code generated by Lark OpenAPI.

from .v1.resource import *


class EventService(object):
    def __init__(self, config: Config) -> None:
        self.v1: V1 = V1(config)


class V1(object):
    def __init__(self, config: Config) -> None:
        self.outbound_ip: Optional[OutboundIp] = OutboundIp(config)
