from .app import *
from .block_role import *
from .department_id import *
from .ext_info import *
from .icon import *
from .meta import *
from .other_rec_rule import *
from .rec_rule import *
from .rec_rule_condition import *
from .role import *
from .table_role import *
from .template_info import *
from .create_app_role_request import *
from .list_app_role_request import *
from .update_app_role_request import *
from .create_app_role_response_body import *
from .create_app_role_response import *
from .list_app_role_response_body import *
from .list_app_role_response import *
from .update_app_role_response_body import *
from .update_app_role_response import *
