# Code generated by Lark OpenAPI.

from typing import Any, Optional, Union, Dict, List, Set, IO, Callable, Type
from lark_oapi.core.construct import init


class LocationCell(object):
    _types = {
        "full_address": str,
        "lat": float,
        "lng": float,
    }

    def __init__(self, d=None):
        self.full_address: Optional[str] = None
        self.lat: Optional[float] = None
        self.lng: Optional[float] = None
        init(self, d, self._types)

    @staticmethod
    def builder() -> "LocationCellBuilder":
        return LocationCellBuilder()


class LocationCellBuilder(object):
    def __init__(self) -> None:
        self._location_cell = LocationCell()

    def full_address(self, full_address: str) -> "LocationCellBuilder":
        self._location_cell.full_address = full_address
        return self

    def lat(self, lat: float) -> "LocationCellBuilder":
        self._location_cell.lat = lat
        return self

    def lng(self, lng: float) -> "LocationCellBuilder":
        self._location_cell.lng = lng
        return self

    def build(self) -> "LocationCell":
        return self._location_cell
